# Generated by Django 5.0.6 on 2026-10-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_article_est_reserve_aux_menus_groupeoption_and_more'),
        ('users', '0019_alter_numeroverifie_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifie_par_role', models.CharField(blank=True, choices=[('restaurateur', 'Restaurateur'), ('admin', 'Admin')], max_length=12, verbose_name='modifié par (rôle)')),
                ('modifie_par_nom', models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('nature', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire (jour de semaine)'), ('date', 'Daté (un jour précis)')], max_length=15, verbose_name='nature')),
                ('jour_semaine', models.PositiveSmallIntegerField(blank=True, help_text='1 à 7, lundi = 1. Requis si nature = hebdomadaire.', null=True, verbose_name='jour de la semaine')),
                ('date', models.DateField(blank=True, help_text='Requis si nature = date.', null=True, verbose_name='date')),
                ('service', models.CharField(choices=[('midi', 'Midi'), ('soir', 'Soir'), ('journee', 'Journée')], max_length=10, verbose_name='service')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('titre', models.CharField(blank=True, max_length=150, verbose_name='titre')),
                ('publie', models.BooleanField(default=False, verbose_name='publié')),
                ('heure_limite_commande', models.TimeField(blank=True, null=True, verbose_name='heure limite de commande')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'menu programmé',
                'verbose_name_plural': 'menus programmés',
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifie_par_role', models.CharField(blank=True, choices=[('restaurateur', 'Restaurateur'), ('admin', 'Admin')], max_length=12, verbose_name='modifié par (rôle)')),
                ('modifie_par_nom', models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('prix_menu', models.DecimalField(blank=True, decimal_places=0, help_text='Vide = prix de base du plat.', max_digits=12, null=True, verbose_name='prix dans le menu (FCFA)')),
                ('stock_initial', models.PositiveIntegerField(blank=True, help_text='Vide = illimité. Repart de cette valeur chaque jour.', null=True, verbose_name='stock initial (par jour)')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_menu', to='catalog.article', verbose_name='plat')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurants.menuprogramme', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'ligne de menu',
                'verbose_name_plural': 'lignes de menu',
                'ordering': ['menu', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProfilRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifie_par_role', models.CharField(blank=True, choices=[('restaurateur', 'Restaurateur'), ('admin', 'Admin')], max_length=12, verbose_name='modifié par (rôle)')),
                ('modifie_par_nom', models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('ferme_exceptionnellement', models.BooleanField(default=False, verbose_name='fermé exceptionnellement')),
                ('motif_fermeture', models.CharField(blank=True, max_length=255, verbose_name='motif de fermeture')),
                ('ferme_jusqu_au', models.DateField(blank=True, null=True, verbose_name="fermé jusqu'au")),
                ('services', models.JSONField(blank=True, default=list, help_text='Liste parmi : sur_place, emporter, livraison.', verbose_name='services proposés')),
                ('delai_preparation_min', models.PositiveIntegerField(default=20, verbose_name='délai de préparation (min)')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('adresse_reperes', models.TextField(blank=True, help_text='Ex. "en face de la pharmacie, 2e rue à droite".', verbose_name='adresse détaillée / repères')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('specialites', models.JSONField(blank=True, default=list, help_text='Liste courte, ex. ["Garba", "Grillades", "Pizza"].', verbose_name='spécialités')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('partenaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_restaurant', to='users.profilpartenaire', verbose_name='partenaire')),
            ],
            options={
                'verbose_name': 'profil restaurant',
                'verbose_name_plural': 'profils restaurant',
            },
        ),
        migrations.AddField(
            model_name='menuprogramme',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.profilrestaurant', verbose_name='restaurant'),
        ),
        migrations.CreateModel(
            name='StockJournalierLigneMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('restant', models.PositiveIntegerField(verbose_name='stock restant')),
                ('ligne_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_jour', to='restaurants.lignemenu', verbose_name='ligne de menu')),
            ],
            options={
                'verbose_name': 'stock journalier de ligne de menu',
                'verbose_name_plural': 'stocks journaliers de ligne de menu',
            },
        ),
        migrations.CreateModel(
            name='TelephoneRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, verbose_name='libellé')),
                ('numero', models.CharField(max_length=20, verbose_name='numéro')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='restaurants.profilrestaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'téléphone de restaurant',
                'verbose_name_plural': 'téléphones de restaurant',
                'ordering': ['restaurant', 'ordre'],
            },
        ),
        migrations.AddIndex(
            model_name='menuprogramme',
            index=models.Index(fields=['restaurant', 'nature', 'service', 'publie'], name='restaurants_restaur_55857a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuprogramme',
            index=models.Index(fields=['restaurant', 'date', 'service'], name='restaurants_restaur_f7faf8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuprogramme',
            index=models.Index(fields=['restaurant', 'jour_semaine', 'service'], name='restaurants_restaur_1c04c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuprogramme',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('date__isnull', True), ('jour_semaine__isnull', False), ('nature', 'hebdomadaire')), models.Q(('date__isnull', False), ('jour_semaine__isnull', True), ('nature', 'date')), _connector='OR'), name='menu_nature_coherente'),
        ),
        migrations.AddConstraint(
            model_name='stockjournalierlignemenu',
            constraint=models.UniqueConstraint(fields=('ligne_menu', 'date'), name='unique_stock_jour_par_ligne'),
        ),
    ]
