# Generated by Django 5.0.6 on 2026-10-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilrestaurant',
            name='whatsapp',
        ),
    ]
