# Generated by Django 5.0.6 on 2026-06-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0004_adresseclient_horaireouverture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: PFR-2026-00125 (généré automatiquement).', max_length=30, unique=True, verbose_name='numéro de commande')),
                ('mode_livraison', models.CharField(choices=[('emporter', 'À emporter'), ('sur_place', 'Sur place'), ('livraison', 'Livraison')], default='emporter', max_length=20, verbose_name='mode de livraison')),
                ('adresse_snapshot', models.CharField(blank=True, help_text="Copie figée de l'adresse au moment de la commande.", max_length=500, verbose_name='adresse (snapshot)')),
                ('heure_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='heure souhaitée')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('expiree', 'Expirée (non récupérée)')], default='nouvelle', max_length=20, verbose_name='statut')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('sous_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='sous-total (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='frais de livraison (FCFA)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money')], default='cash', help_text='À titre informatif (pas de paiement intégré en MVP).', max_length=30, verbose_name='mode de paiement')),
                ('notes_client', models.TextField(blank=True, verbose_name='notes du client')),
                ('notes_commercant', models.TextField(blank=True, verbose_name='notes du commerçant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True, verbose_name='acceptée le')),
                ('prete_le', models.DateTimeField(blank=True, null=True, verbose_name='prête le')),
                ('livree_le', models.DateTimeField(blank=True, null=True, verbose_name='livrée le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='users.adresseclient', verbose_name='adresse de livraison')),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='users.profilcommercant', verbose_name='commerçant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200, verbose_name="nom de l'article")),
                ('variante_nom', models.CharField(blank=True, max_length=50, verbose_name='nom de la variante')),
                ('supplements', models.JSONField(blank=True, default=list, help_text='Snapshot des suppléments choisis [{nom, prix}…].', verbose_name='suppléments')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='prix unitaire (FCFA)')),
                ('prix_ligne', models.DecimalField(decimal_places=0, help_text='quantité × prix_unitaire (+ éventuels suppléments).', max_digits=12, verbose_name='prix de la ligne (FCFA)')),
                ('note_speciale', models.TextField(blank=True, verbose_name='note spéciale')),
                ('article', models.ForeignKey(blank=True, help_text="Peut être null si l'article a été supprimé après commande.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='catalog.article', verbose_name='article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'ordering': ['commande', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='users.profilcommercant', verbose_name='commerçant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'panier',
                'verbose_name_plural': 'paniers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante_id', models.IntegerField(blank=True, help_text='ID de la Variante sélectionnée (Petit/Moyen/Grand).', null=True, verbose_name='variante choisie')),
                ('supplements', models.JSONField(blank=True, default=list, help_text="Liste d'objets [{id, nom, prix}…] figés au moment de l'ajout.", verbose_name='suppléments choisis')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, help_text="Snapshot au moment de l'ajout au panier.", max_digits=12, verbose_name='prix unitaire (FCFA)')),
                ('note_speciale', models.TextField(blank=True, help_text='Ex: "Sans oignons s\'il vous plaît".', verbose_name='note spéciale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='catalog.article', verbose_name='article')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.panier', verbose_name='panier')),
            ],
            options={
                'verbose_name': 'ligne de panier',
                'verbose_name_plural': 'lignes de panier',
                'ordering': ['panier', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['commercant', 'statut', '-created_at'], name='orders_comm_commerc_eed57a_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['user', '-created_at'], name='orders_comm_user_id_bc8890_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='orders_comm_statut_68f2e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(fields=('user', 'commercant'), name='unique_panier_par_couple'),
        ),
    ]
