# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='users.adresseclient', verbose_name='adresse de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par'),
        ),
        migrations.AddField(
            model_name='commande',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(blank=True, help_text="Peut être null si l'article a été supprimé après commande.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande', verbose_name='commande'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='panier',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.panier', verbose_name='panier'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['partenaire', 'statut', '-created_at'], name='orders_comm_partena_77f915_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['user', '-created_at'], name='orders_comm_user_id_bc8890_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='orders_comm_statut_68f2e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(fields=('user', 'partenaire'), name='unique_panier_par_couple'),
        ),
    ]
