# Generated by Django 5.0.6 on 2026-07-17 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('orders', '0002_initial'),
        ('users', '0002_sessionappareil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='panier',
            name='unique_panier_par_couple',
        ),
        migrations.AddField(
            model_name='panier',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='catalog.categorie', verbose_name='catégorie'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(fields=('user', 'partenaire', 'categorie'), name='unique_panier_par_triplet'),
        ),
    ]
