# Generated by Django 5.0.6 on 2026-08-15 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_panier_unique_panier_par_couple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='localisation_livraison',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Point GPS capturé quand le client choisit "je veux être livré". Obligatoire si mode_livraison=livraison. Sert au livreur (point B).', null=True, srid=4326, verbose_name='position GPS de livraison'),
        ),
    ]
