# Generated by Django 5.0.6 on 2026-09-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commande_localisation_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAdminCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='texte')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_admin', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'note admin sur commande',
                'verbose_name_plural': 'notes admin sur commandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('expiree', 'Expirée (non récupérée)')], max_length=20, verbose_name='statut atteint')),
                ('acteur_role', models.CharField(choices=[('client', 'Client'), ('partenaire', 'Partenaire'), ('admin', 'Admin')], max_length=12, verbose_name="rôle de l'acteur")),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'historique de commande',
                'verbose_name_plural': 'historiques de commande',
                'ordering': ['cree_le'],
                'indexes': [models.Index(fields=['commande', 'cree_le'], name='orders_hist_command_fd0589_idx')],
            },
        ),
    ]
