# Generated by Django 5.0.6 on 2026-10-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_noteadmincommande_historiquecommande'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='ligne_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='restaurants.lignemenu', verbose_name='ligne de menu (si commandé depuis un menu)'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='ligne_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_panier', to='restaurants.lignemenu', verbose_name='ligne de menu (si commandé depuis un menu)'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='supplements',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot des suppléments/options choisis [{nom, prix, groupe_libelle?}…].', verbose_name='suppléments'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='supplements',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'objets [{id, nom, prix}…] figés au moment de l'ajout. Sert aussi aux options de GroupeOption (restaurants) : [{id, nom, prix, groupe_id, groupe_libelle}…], mêmes clés de base, groupe_id/groupe_libelle en plus (ignorés du code existant qui ne lit que nom/prix).", verbose_name='suppléments choisis'),
        ),
    ]
