# Generated by Django 5.0.6 on 2026-10-07 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_locations_m1'),
        ('users', '0021_position_partenaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='numéro')),
                ('nature', models.CharField(choices=[('visite', 'Visite'), ('reservation', 'Réservation')], max_length=15, verbose_name='nature')),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='date souhaitée (visite)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début (réservation)')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin (réservation)')),
                ('nb_personnes', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de personnes')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, verbose_name='téléphone de contact')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='nouvelle', max_length=12, verbose_name='statut')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('confirmee_le', models.DateTimeField(blank=True, null=True, verbose_name='confirmée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reservation', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reservation', to='catalog.article', verbose_name='objet (logement, véhicule…)')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reservation', to='users.profilpartenaire', verbose_name='partenaire')),
            ],
            options={
                'verbose_name': 'demande de visite/réservation',
                'verbose_name_plural': 'demandes de visite/réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], max_length=12, verbose_name='statut atteint')),
                ('acteur_role', models.CharField(choices=[('client', 'Client'), ('loueur', 'Loueur'), ('admin', 'Admin')], max_length=10, verbose_name="rôle de l'acteur")),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='reservations.demandereservation', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'historique de demande',
                'verbose_name_plural': 'historiques de demande',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='NoteAdminDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='texte')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_admin', to='reservations.demandereservation', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'note admin de demande',
                'verbose_name_plural': 'notes admin de demande',
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='demandereservation',
            index=models.Index(fields=['partenaire', 'statut', '-created_at'], name='reservation_partena_6dbe5f_idx'),
        ),
        migrations.AddIndex(
            model_name='demandereservation',
            index=models.Index(fields=['client', '-created_at'], name='reservation_client__2b8da7_idx'),
        ),
        migrations.AddIndex(
            model_name='demandereservation',
            index=models.Index(fields=['statut'], name='reservation_statut_37dfca_idx'),
        ),
    ]
