# Generated by Django 5.0.6 on 2026-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandereservation",
            name="avec_chauffeur",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="avec chauffeur"
            ),
        ),
        migrations.AddField(
            model_name="demandereservation",
            name="lieu_prise_en_charge",
            field=models.TextField(blank=True, verbose_name="lieu de prise en charge"),
        ),
        migrations.AddField(
            model_name="demandereservation",
            name="montant_estime",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Calculé à la création (jours × prix/jour).",
                max_digits=12,
                null=True,
                verbose_name="montant estimé (FCFA)",
            ),
        ),
    ]
