# Generated by Django 5.0.6 on 2026-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_locations_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandereservation",
            name="nb_adultes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nombre d'adultes"
            ),
        ),
        migrations.AddField(
            model_name="demandereservation",
            name="nb_enfants",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nombre d'enfants"
            ),
        ),
        migrations.AddField(
            model_name="demandereservation",
            name="nb_unites",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="nombre d'unités (chambres)"
            ),
        ),
        migrations.AlterField(
            model_name="demandereservation",
            name="montant_estime",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Calculé à la création (jours × prix/jour ; nuits × prix × unités pour un hébergement).",
                max_digits=12,
                null=True,
                verbose_name="montant estimé (FCFA)",
            ),
        ),
    ]
