from django.urls import include, path

from .views_parametres import (
    CategoriesParametresView, OrdreCategoriesView, RechercheCategorieDetailView,
    RechercheCategoriesView, RechercheSansResultatView, TesterRechercheView,
    TraiterSansResultatView, VisibiliteCategorieView,
)
from .views_categories import (
    CategoriesAdminListCreateView, CategorieAdminDetailView, CategorieArchiverView,
    TypesPartenaireCategoriesView,
)
from .views_position import PositionPartenaireView
from .views_telephone import ChangerTelephonePartenaireView, HistoriqueTelephonePartenaireView
from .views import (DashboardG5View, AppareilsExportView, ModerationView,
                    JournalModerationView, JournalExportView,
                    IndicateursPartenairesView, PartenairesExportView,
                    FaveurView, FaveurPubliciteView,
                    DemandesPartenariatView, MesPermissionsView,
                    ChangerFormulePubliciteView, RecherchePartenairesView,
                    CreditsPartenaireView, CreditDetailView,
                    RechercheComptesView, AdminsListView,
                    CreerAdminView, AdminDetailView,
                    InterventionsAdminView, InterventionsAdminExportView,
                    PartenairesListeAdminView, PartenairesListeAdminExportView,
                    ConnexionsAdminView, ConnexionsAdminExportView)

app_name = 'administration'

urlpatterns = [
    path('categories/', CategoriesAdminListCreateView.as_view(), name='categories'),
    path('categories/ordre/', OrdreCategoriesView.as_view(), name='categories-ordre'),
    path('categories/types-partenaire/', TypesPartenaireCategoriesView.as_view(), name='categories-types'),
    path('categories/<int:pk>/', CategorieAdminDetailView.as_view(), name='categorie-detail'),
    path('categories/<int:pk>/archiver/', CategorieArchiverView.as_view(), name='categorie-archiver'),
    path('parametres/recherche/categories/', RechercheCategoriesView.as_view(), name='parametres-recherche-categories'),
    path('parametres/recherche/categories/<int:pk>/', RechercheCategorieDetailView.as_view(),
         name='parametres-recherche-categorie'),
    path('parametres/recherche/sans-resultat/', RechercheSansResultatView.as_view(),
         name='parametres-sans-resultat'),
    path('parametres/recherche/sans-resultat/<int:pk>/traiter/', TraiterSansResultatView.as_view(),
         name='parametres-sans-resultat-traiter'),
    path('parametres/recherche/tester/', TesterRechercheView.as_view(), name='parametres-recherche-tester'),
    path('parametres/categories/', CategoriesParametresView.as_view(), name='parametres-categories'),
    path('parametres/categories/ordre/', OrdreCategoriesView.as_view(), name='parametres-categories-ordre'),
    path('parametres/categories/<int:pk>/', VisibiliteCategorieView.as_view(),
         name='parametres-categorie-visibilite'),
    path('mes-permissions/', MesPermissionsView.as_view(), name='mes-permissions'),
    path('dashboard/', DashboardG5View.as_view(), name='dashboard'),
    path('appareils/export/', AppareilsExportView.as_view(), name='appareils-export'),
    path('moderation/', ModerationView.as_view(), name='moderation'),
    path('moderation/journal/', JournalModerationView.as_view(), name='moderation-journal'),
    path('moderation/journal/export/', JournalExportView.as_view(), name='moderation-journal-export'),
    path('partenaires/', IndicateursPartenairesView.as_view(), name='partenaires'),
    path('partenaires/export/', PartenairesExportView.as_view(), name='partenaires-export'),
    path('partenaires/liste/', PartenairesListeAdminView.as_view(), name='partenaires-liste'),
    path('partenaires/liste/export/', PartenairesListeAdminExportView.as_view(),
         name='partenaires-liste-export'),
    path('partenaires/<int:pk>/faveur/', FaveurView.as_view(), name='partenaire-faveur'),
    path('partenaires/<int:pk>/changer-telephone/', ChangerTelephonePartenaireView.as_view(),
         name='partenaire-changer-telephone'),
    path('partenaires/<int:pk>/position/', PositionPartenaireView.as_view(), name='partenaire-position'),
    path('partenaires/<int:pk>/historique-telephone/', HistoriqueTelephonePartenaireView.as_view(),
         name='partenaire-historique-telephone'),
    path('publicites/<uuid:pk>/faveur/', FaveurPubliciteView.as_view(), name='publicite-faveur'),
    path('publicites/<uuid:pk>/formule/', ChangerFormulePubliciteView.as_view(), name='publicite-formule'),
    path('partenaires/recherche/', RecherchePartenairesView.as_view(), name='partenaires-recherche'),
    path('partenaires/<int:pk>/credits/', CreditsPartenaireView.as_view(), name='partenaire-credits'),
    path('credits/<uuid:pk>/', CreditDetailView.as_view(), name='credit-detail'),
    path('comptes/recherche/', RechercheComptesView.as_view(), name='comptes-recherche'),
    path('admins/', AdminsListView.as_view(), name='admins-liste'),
    path('admins/creer/', CreerAdminView.as_view(), name='admins-creer'),
    path('admins/<int:pk>/', AdminDetailView.as_view(), name='admin-detail'),
    path('demandes-partenariat/', DemandesPartenariatView.as_view(), name='demandes-partenariat'),
    path('interventions/', InterventionsAdminView.as_view(), name='interventions'),
    path('interventions/export/', InterventionsAdminExportView.as_view(),
         name='interventions-export'),
    path('connexions-admin/', ConnexionsAdminView.as_view(), name='connexions-admin'),
    path('connexions-admin/export/', ConnexionsAdminExportView.as_view(),
         name='connexions-admin-export'),
    path('geo/', include('apps.geo.admin_urls')),
]
