# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: INT-2026-00042', max_length=30, unique=True, verbose_name='numéro')),
                ('type_intervention', models.CharField(choices=[('reparation', 'Réparation'), ('installation', 'Installation'), ('depannage_urgent', 'Dépannage urgent'), ('devis', 'Demande de devis'), ('autre', 'Autre')], default='reparation', max_length=30, verbose_name="type d'intervention")),
                ('type_libre', models.CharField(blank=True, max_length=200, verbose_name='précision (si type = autre)')),
                ('description', models.TextField(verbose_name='description du problème')),
                ('urgence', models.CharField(choices=[('urgent', 'Urgent (dans la journée)'), ('cette_semaine', 'Cette semaine'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='urgence')),
                ('adresse_snapshot', models.CharField(blank=True, max_length=500, verbose_name='adresse (snapshot)')),
                ('description_acces', models.TextField(blank=True, verbose_name='comment trouver le lieu')),
                ('disponibilite_preferee', models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi'), ('soir', 'Soir'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20, verbose_name='disponibilité préférée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('date_proposee', models.DateTimeField(blank=True, null=True, verbose_name="date proposée par l'artisan")),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='prix proposé (FCFA)')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True, verbose_name='acceptée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "demande d'intervention",
                'verbose_name_plural': "demandes d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeInterventionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interventions/', verbose_name='photo')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "photo de demande d'intervention",
                'verbose_name_plural': "photos de demandes d'intervention",
                'ordering': ['demande', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('audio', 'Audio'), ('systeme', 'Message système')], default='texte', max_length=10, verbose_name='type')),
                ('contenu', models.TextField(blank=True, verbose_name='contenu')),
                ('media_url', models.CharField(blank=True, help_text='Pour les messages de type image ou audio.', max_length=500, verbose_name='URL du média')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('livre', 'Livré'), ('lu', 'Lu')], default='envoye', max_length=10, verbose_name='statut')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='dernière activité')),
                ('est_archivee', models.BooleanField(default=False, verbose_name='archivée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, help_text='Contexte facultatif : article concerné par la discussion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-derniere_activite'],
            },
        ),
    ]
