# Generated by Django 5.0.6 on 2026-06-11 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0004_adresseclient_horaireouverture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='dernière activité')),
                ('est_archivee', models.BooleanField(default=False, verbose_name='archivée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, help_text='Contexte facultatif : article concerné par la discussion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='catalog.article', verbose_name='article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_client', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.profilcommercant', verbose_name='commerçant')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: INT-2026-00042', max_length=30, unique=True, verbose_name='numéro')),
                ('type_intervention', models.CharField(choices=[('reparation', 'Réparation'), ('installation', 'Installation'), ('depannage_urgent', 'Dépannage urgent'), ('devis', 'Demande de devis'), ('autre', 'Autre')], default='reparation', max_length=30, verbose_name="type d'intervention")),
                ('type_libre', models.CharField(blank=True, max_length=200, verbose_name='précision (si type = autre)')),
                ('description', models.TextField(verbose_name='description du problème')),
                ('urgence', models.CharField(choices=[('urgent', 'Urgent (dans la journée)'), ('cette_semaine', 'Cette semaine'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='urgence')),
                ('adresse_snapshot', models.CharField(blank=True, max_length=500, verbose_name='adresse (snapshot)')),
                ('description_acces', models.TextField(blank=True, verbose_name='comment trouver le lieu')),
                ('disponibilite_preferee', models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi'), ('soir', 'Soir'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20, verbose_name='disponibilité préférée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('date_proposee', models.DateTimeField(blank=True, null=True, verbose_name="date proposée par l'artisan")),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='prix proposé (FCFA)')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True, verbose_name='acceptée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_intervention', to='users.adresseclient', verbose_name="adresse de l'intervention")),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_recues', to='users.profilcommercant', verbose_name='artisan')),
                ('conversation', models.OneToOneField(blank=True, help_text='Conversation créée automatiquement pour la négociation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_intervention', to='messaging.conversation', verbose_name='conversation associée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_intervention', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': "demande d'intervention",
                'verbose_name_plural': "demandes d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeInterventionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interventions/', verbose_name='photo')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='messaging.demandeintervention', verbose_name="demande d'intervention")),
            ],
            options={
                'verbose_name': "photo de demande d'intervention",
                'verbose_name_plural': "photos de demandes d'intervention",
                'ordering': ['demande', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('audio', 'Audio'), ('systeme', 'Message système')], default='texte', max_length=10, verbose_name='type')),
                ('contenu', models.TextField(blank=True, verbose_name='contenu')),
                ('media_url', models.CharField(blank=True, help_text='Pour les messages de type image ou audio.', max_length=500, verbose_name='URL du média')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('livre', 'Livré'), ('lu', 'Lu')], default='envoye', max_length=10, verbose_name='statut')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='conversation')),
                ('expediteur', models.ForeignKey(blank=True, help_text='Null pour les messages système.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', '-derniere_activite'], name='messaging_c_client__0516a9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['commercant', '-derniere_activite'], name='messaging_c_commerc_ebafaa_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['artisan', 'statut', '-created_at'], name='messaging_d_artisan_dc2bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['user', '-created_at'], name='messaging_d_user_id_3ffafe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'),
        ),
    ]
