# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_client', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_intervention', to='users.adresseclient', verbose_name="adresse de l'intervention"),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_recues', to='users.profilpartenaire', verbose_name='artisan'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text='Conversation créée automatiquement pour la négociation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_intervention', to='messaging.conversation', verbose_name='conversation associée'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_intervention', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='demandeinterventionphoto',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='messaging.demandeintervention', verbose_name="demande d'intervention"),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, help_text='Null pour les messages système.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', '-derniere_activite'], name='messaging_c_client__0516a9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['partenaire', '-derniere_activite'], name='messaging_c_partena_220516_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['artisan', 'statut', '-created_at'], name='messaging_d_artisan_dc2bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['user', '-created_at'], name='messaging_d_user_id_3ffafe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'),
        ),
    ]
