# Generated by Django 5.0.6 on 2026-07-21 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0002_sessionappareil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulePublicite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prix', models.PositiveIntegerField(verbose_name='prix (FCFA)')),
                ('priorite', models.PositiveIntegerField(default=0, help_text='Plus élevé = passe avant dans le carrousel', verbose_name='priorité')),
                ('est_active', models.BooleanField(default=True, verbose_name='formule active')),
                ('duree_jours', models.PositiveIntegerField(default=1, verbose_name='durée (jours)')),
                ('passages_par_jour', models.PositiveIntegerField(default=1, verbose_name='passages par jour')),
                ('duree_affichage_secondes', models.PositiveIntegerField(default=5, verbose_name="durée d'un passage (s)")),
                ('quota_partenaires', models.PositiveIntegerField(default=50, help_text='1 = exclusivité totale', verbose_name='quota de partenaires simultanés')),
                ('acces_heures_affluence', models.BooleanField(default=False, verbose_name="accès aux heures d'affluence")),
                ('types_affichage', models.JSONField(default=list, help_text='Liste parmi : carrousel, interstitiel, bandeau_bas, page_publicites', verbose_name="types d'affichage autorisés")),
                ('nb_images_max', models.PositiveIntegerField(default=1, verbose_name="nombre d'images max")),
                ('video_autorisee', models.BooleanField(default=False, verbose_name='vidéo autorisée')),
                ('duree_video_max_secondes', models.PositiveIntegerField(default=30, verbose_name='durée vidéo max (s)')),
                ('cible_pourcentage_actifs', models.PositiveIntegerField(blank=True, help_text="Ex. 80 : la pub reste active jusqu'à toucher 80% des clients actifs. Vide = pas de garantie.", null=True, verbose_name='cible % clients actifs')),
            ],
            options={
                'verbose_name': 'formule de publicité',
                'verbose_name_plural': 'formules de publicité',
                'ordering': ['-priorite', '-prix'],
            },
        ),
        migrations.CreateModel(
            name='ParametresPublicite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('affluence_debut', models.TimeField(default='18:00', verbose_name="début heures d'affluence")),
                ('affluence_fin', models.TimeField(default='21:00', verbose_name="fin heures d'affluence")),
                ('calcul_affluence_auto', models.BooleanField(default=False, verbose_name="calcul automatique des heures d'affluence (analytics)")),
                ('intervalle_min_interstitiel_secondes', models.PositiveIntegerField(default=300, verbose_name='intervalle min entre 2 interstitiels (s)')),
                ('validation_auto', models.BooleanField(default=False, verbose_name='validation automatique après paiement')),
            ],
            options={
                'verbose_name': 'paramètres publicité',
                'verbose_name_plural': 'paramètres publicité',
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image_couverture', models.ImageField(help_text='Flyer/affiche affichée dans le carrousel et les listes', upload_to='publicites/couvertures/', verbose_name='image de couverture')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicites/videos/', verbose_name='vidéo')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente_validation', 'En attente de validation'), ('active', 'Active'), ('terminee', 'Terminée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=25, verbose_name='statut')),
                ('debut_diffusion', models.DateTimeField(blank=True, null=True, verbose_name='début de diffusion')),
                ('fin_diffusion', models.DateTimeField(blank=True, null=True, verbose_name='fin de diffusion')),
                ('nb_personnes_touchees', models.PositiveIntegerField(default=0, verbose_name='personnes touchées')),
                ('nb_impressions', models.PositiveIntegerField(default=0, verbose_name='impressions totales')),
                ('nb_clics', models.PositiveIntegerField(default=0, verbose_name='clics')),
                ('stats_visibles_partenaire', models.BooleanField(default=False, verbose_name='stats visibles par le partenaire')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicites', to='publicites.formulepublicite', verbose_name='formule')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicites', to='payments.paiement')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicites', to='users.profilpartenaire', verbose_name='partenaire')),
            ],
            options={
                'verbose_name': 'publicité',
                'verbose_name_plural': 'publicités',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ImagePublicite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='publicites/images/', verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('publicite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publicites.publicite', verbose_name='publicité')),
            ],
            options={
                'verbose_name': 'image de publicité',
                'verbose_name_plural': 'images de publicité',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ImpressionPublicite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_affichage', models.CharField(choices=[('carrousel', 'Carrousel (accueil)'), ('interstitiel', 'Interstitiel (70-80% écran)'), ('bandeau_bas', 'Bandeau bas transparent'), ('page_publicites', 'Page Publicités')], default='carrousel', max_length=20, verbose_name="type d'affichage")),
                ('minute_session', models.PositiveIntegerField(blank=True, null=True, verbose_name='minute de session')),
                ('cliquee', models.BooleanField(default=False, verbose_name='cliquée')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions_publicites', to=settings.AUTH_USER_MODEL)),
                ('publicite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='publicites.publicite', verbose_name='publicité')),
            ],
            options={
                'verbose_name': 'impression de publicité',
                'verbose_name_plural': 'impressions de publicité',
                'indexes': [models.Index(fields=['publicite', 'utilisateur'], name='publicites__publici_047669_idx')],
            },
        ),
    ]
