# Generated by Django 5.0.6 on 2026-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrespublicite',
            name='interstitiel_minute_max',
            field=models.PositiveIntegerField(default=15, help_text='Au-dela de cette duree moyenne, on utilise la minute nominale', verbose_name='interstitiel : borne haute du creneau'),
        ),
        migrations.AddField(
            model_name='parametrespublicite',
            name='interstitiel_minute_min',
            field=models.PositiveIntegerField(default=10, help_text='Minute a laquelle servir la pub aux sessions longues', verbose_name='interstitiel : minute nominale'),
        ),
        migrations.AddField(
            model_name='parametrespublicite',
            name='interstitiel_ratio_session_courte',
            field=models.PositiveIntegerField(default=70, help_text='Session courte : pub servie a ce pourcentage de la duree habituelle', verbose_name='interstitiel : % de la session courte'),
        ),
    ]
