# Generated by Django 5.0.6 on 2026-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0002_parametrespublicite_interstitiel_minute_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulepublicite',
            name='passages_par_type',
            field=models.JSONField(blank=True, default=dict, help_text='Facultatif. Ex. {"carrousel": 6, "interstitiel": 3, "bandeau_bas": 4}. Vide = le quota global "passages par jour" s\'applique à tous les emplacements confondus, et le carrousel peut alors épuiser la place réservée à l\'interstitiel.', verbose_name='passages par jour et par emplacement'),
        ),
    ]
