# Generated by Django 5.0.6 on 2026-07-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_profilnavigation_nb_interactions_mois_and_more'),
        ('publicites', '0003_formulepublicite_passages_par_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impressionpublicite',
            name='session',
            field=models.ForeignKey(blank=True, help_text="Permet de ne compter qu'une impression par session et par emplacement : sans cela, un simple retour sur l'accueil regonfle artificiellement les compteurs.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions_publicites', to='analytics.tempssessionutilisateur', verbose_name='session'),
        ),
        migrations.AddIndex(
            model_name='impressionpublicite',
            index=models.Index(fields=['session', 'publicite', 'type_affichage'], name='publicites__session_d34b86_idx'),
        ),
    ]
