# Generated by Django 5.0.6 on 2026-07-24 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_profilnavigation_nb_interactions_mois_and_more'),
        ('payments', '0001_initial'),
        ('publicites', '0004_impressionpublicite_session_and_more'),
        ('users', '0003_profilpartenaire_nb_vues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='impressionpublicite',
            index=models.Index(fields=['utilisateur', 'cree_le'], name='publicites__utilisa_dea216_idx'),
        ),
        migrations.AddIndex(
            model_name='publicite',
            index=models.Index(fields=['statut', 'debut_diffusion'], name='publicites__statut_335b2e_idx'),
        ),
    ]
