# Generated by Django 5.0.6 on 2026-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0005_impressionpublicite_publicites__utilisa_dea216_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='portee',
            field=models.CharField(choices=[('departement', 'Departement seulement'), ('region', 'Toute la region'), ('district', 'Tout le district')], default='departement', help_text='Étendue géographique achetée pour cette campagne. La portée réellement appliquée est le maximum entre cette valeur et la portée du forfait du partenaire (une pub ne descend jamais sous le forfait).', max_length=15, verbose_name='portée achetée'),
        ),
    ]
