# Generated by Django 5.0.6 on 2026-08-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0006_publicite_portee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='est_faveur',
            field=models.BooleanField(default=False, help_text='Campagne diffusée gratuitement, sans paiement.', verbose_name='campagne offerte'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='faveur_accordee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicites_offertes', to=settings.AUTH_USER_MODEL, verbose_name='faveur accordée par'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='faveur_motif',
            field=models.TextField(blank=True, help_text='Ex: "Partenariat", "Lancement", "Compensation".', verbose_name='motif de la faveur'),
        ),
    ]
