# Generated by Django 5.0.6 on 2026-08-20 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0007_publicite_est_faveur_publicite_faveur_accordee_par_and_more'),
        ('users', '0015_parametressecurite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditFormulePub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('consomme', 'Consommé')], default='disponible', max_length=20, verbose_name='statut')),
                ('motif', models.TextField(blank=True, verbose_name='motif')),
                ('consomme_le', models.DateTimeField(blank=True, null=True, verbose_name='consommé le')),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_pub_accordes', to=settings.AUTH_USER_MODEL, verbose_name='accordé par')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='publicites.formulepublicite', verbose_name='formule')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_pub', to='users.profilpartenaire', verbose_name='partenaire')),
                ('publicite_consommatrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_utilises', to='publicites.publicite', verbose_name='publicité consommatrice')),
            ],
            options={
                'verbose_name': 'crédit de formule publicitaire',
                'verbose_name_plural': 'crédits de formule publicitaire',
                'ordering': ['-cree_le'],
            },
        ),
    ]
