# Generated by Django 5.0.6 on 2026-08-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0008_credit_formule_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='masquee_par_partenaire',
            field=models.BooleanField(default=False, help_text="Le partenaire l'a retirée de ses propres listes (historique et stats conservés). N'affecte pas la modération admin.", verbose_name='masquée par le partenaire'),
        ),
    ]
