# Generated by Django 5.0.6 on 2026-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0009_masquer_pub_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='stats_visibles_partenaire',
            field=models.BooleanField(default=True, help_text="Visibles par défaut pour les pubs actives et terminées ; l'admin peut les masquer campagne par campagne.", verbose_name='stats visibles par le partenaire'),
        ),
    ]
