# Generated by Django 5.0.6 on 2026-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commande_nouvelle', 'Nouvelle commande'), ('commande_acceptee', 'Commande acceptée'), ('commande_refusee', 'Commande refusée'), ('commande_prete', 'Commande prête'), ('commande_livree', 'Commande livrée'), ('nouveau_message', 'Nouveau message'), ('demande_intervention', "Demande d'intervention"), ('intervention_acceptee', 'Intervention acceptée'), ('nouveau_commentaire', 'Nouveau commentaire'), ('nouveau_like', 'Nouveau like'), ('faveur_accordee', 'Faveur accordée'), ('abonnement_expire', 'Abonnement expirant'), ('signalement_traite', 'Signalement traité'), ('systeme', 'Message système')], max_length=40, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données pour le deep-linking (ex: {"article_id": 42, "commande_id": 7}).', verbose_name='données contextuelles')),
                ('lu', models.BooleanField(default=False, verbose_name='lue')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalementArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam ou publicité abusive'), ('arnaque', "Arnaque, tentative d'escroquerie"), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausses_infos', 'Fausses informations'), ('harcelement', 'Harcèlement, insultes'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='motif')),
                ('description', models.TextField(blank=True, help_text='Détails complémentaires fournis par le rapporteur.', verbose_name='description')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_examen', "En cours d'examen"), ('traite', 'Traité'), ('rejete', 'Rejeté (non fondé)')], default='nouveau', max_length=20, verbose_name='statut')),
                ('action_prise', models.TextField(blank=True, help_text="Notes de l'admin sur l'action effectuée.", verbose_name='action prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
            ],
            options={
                'verbose_name': 'signalement — article',
                'verbose_name_plural': 'signalements — articles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalementCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam ou publicité abusive'), ('arnaque', "Arnaque, tentative d'escroquerie"), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausses_infos', 'Fausses informations'), ('harcelement', 'Harcèlement, insultes'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='motif')),
                ('description', models.TextField(blank=True, help_text='Détails complémentaires fournis par le rapporteur.', verbose_name='description')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_examen', "En cours d'examen"), ('traite', 'Traité'), ('rejete', 'Rejeté (non fondé)')], default='nouveau', max_length=20, verbose_name='statut')),
                ('action_prise', models.TextField(blank=True, help_text="Notes de l'admin sur l'action effectuée.", verbose_name='action prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
            ],
            options={
                'verbose_name': 'signalement — commentaire',
                'verbose_name_plural': 'signalements — commentaires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam ou publicité abusive'), ('arnaque', "Arnaque, tentative d'escroquerie"), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausses_infos', 'Fausses informations'), ('harcelement', 'Harcèlement, insultes'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='motif')),
                ('description', models.TextField(blank=True, help_text='Détails complémentaires fournis par le rapporteur.', verbose_name='description')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_examen', "En cours d'examen"), ('traite', 'Traité'), ('rejete', 'Rejeté (non fondé)')], default='nouveau', max_length=20, verbose_name='statut')),
                ('action_prise', models.TextField(blank=True, help_text="Notes de l'admin sur l'action effectuée.", verbose_name='action prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
            ],
            options={
                'verbose_name': 'signalement — message',
                'verbose_name_plural': 'signalements — messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalementPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam ou publicité abusive'), ('arnaque', "Arnaque, tentative d'escroquerie"), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausses_infos', 'Fausses informations'), ('harcelement', 'Harcèlement, insultes'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='motif')),
                ('description', models.TextField(blank=True, help_text='Détails complémentaires fournis par le rapporteur.', verbose_name='description')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_examen', "En cours d'examen"), ('traite', 'Traité'), ('rejete', 'Rejeté (non fondé)')], default='nouveau', max_length=20, verbose_name='statut')),
                ('action_prise', models.TextField(blank=True, help_text="Notes de l'admin sur l'action effectuée.", verbose_name='action prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
            ],
            options={
                'verbose_name': 'signalement — commerçant',
                'verbose_name_plural': 'signalements — commerçants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
