# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('messaging', '0002_initial'),
        ('moderation', '0001_initial'),
        ('social', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire'),
        ),
        migrations.AddField(
            model_name='signalementarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='catalog.article', verbose_name='article signalé'),
        ),
        migrations.AddField(
            model_name='signalementarticle',
            name='rapporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_articles', to=settings.AUTH_USER_MODEL, verbose_name='rapporteur'),
        ),
        migrations.AddField(
            model_name='signalementarticle',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_articles_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='commentaire_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='social.commentairearticle', verbose_name='commentaire (article)'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='commentaire_partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='social.commentairepartenaire', verbose_name='commentaire (commerçant)'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='rapporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='rapporteur'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_commentaires_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='messaging.message', verbose_name='message signalé'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='rapporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_messages', to=settings.AUTH_USER_MODEL, verbose_name='rapporteur'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_messages_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par'),
        ),
        migrations.AddField(
            model_name='signalementpartenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='users.profilpartenaire', verbose_name='commerçant signalé'),
        ),
        migrations.AddField(
            model_name='signalementpartenaire',
            name='rapporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_partenaires', to=settings.AUTH_USER_MODEL, verbose_name='rapporteur'),
        ),
        migrations.AddField(
            model_name='signalementpartenaire',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_partenaires_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'lu', '-created_at'], name='moderation__user_id_0ca338_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='moderation__user_id_9a10c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalementcommentaire',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commentaire_article__isnull', False), ('commentaire_partenaire__isnull', True)), models.Q(('commentaire_article__isnull', True), ('commentaire_partenaire__isnull', False)), _connector='OR'), name='signalement_commentaire_exclusif'),
        ),
    ]
