# Generated by Django 5.0.6 on 2026-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('commande_nouvelle', 'Nouvelle commande'), ('commande_acceptee', 'Commande acceptée'), ('commande_refusee', 'Commande refusée'), ('commande_prete', 'Commande prête'), ('commande_livree', 'Commande livrée'), ('nouveau_message', 'Nouveau message'), ('demande_intervention', "Demande d'intervention"), ('intervention_acceptee', 'Intervention acceptée'), ('nouveau_commentaire', 'Nouveau commentaire'), ('nouveau_like', 'Nouveau like'), ('faveur_accordee', 'Faveur accordée'), ('abonnement_expire', 'Abonnement expirant'), ('signalement_traite', 'Signalement traité'), ('systeme', 'Message système'), ('pub_soumise', 'Campagne pub soumise'), ('pub_a_valider', 'Campagne pub à valider')], max_length=40, verbose_name='type'),
        ),
    ]
