# Generated by Django 5.0.6 on 2026-06-15 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_sessionappareil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_objet', models.CharField(choices=[('abonnement', 'Abonnement'), ('publicite', 'Publicité'), ('commande', 'Commande'), ('autre', 'Autre')], default='abonnement', max_length=20, verbose_name="type d'objet payé")),
                ('objet_id', models.CharField(blank=True, help_text="ID libre de l'élément payé (abonnement, commande, pub).", max_length=64, verbose_name="référence de l'objet")),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant (FCFA)')),
                ('mode', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave'), ('virement', 'Virement bancaire')], default='cash', max_length=20, verbose_name='mode')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('rejete', 'Rejeté'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='statut')),
                ('reference_externe', models.CharField(blank=True, help_text="ID de transaction mobile money / banque (rempli à l'intégration réelle).", max_length=128, verbose_name='référence opérateur')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='users.profilpartenaire', verbose_name='partenaire concerné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='payeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par (admin)')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['statut', '-cree_le'], name='payments_pa_statut_560588_idx'), models.Index(fields=['user', '-cree_le'], name='payments_pa_user_id_79ff1c_idx'), models.Index(fields=['type_objet', 'objet_id'], name='payments_pa_type_ob_7ccf1d_idx')],
            },
        ),
    ]
