# Generated by Django 5.0.6 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0021_position_partenaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilEtablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_etablissement",
                    models.CharField(
                        choices=[
                            ("hotel", "Hôtel"),
                            ("residence_meublee", "Résidence meublée"),
                            ("auberge", "Auberge"),
                            ("motel", "Motel"),
                            ("autre", "Autre"),
                        ],
                        default="hotel",
                        max_length=20,
                        verbose_name="type d'établissement",
                    ),
                ),
                (
                    "etoiles",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="étoiles (0-5)"
                    ),
                ),
                (
                    "heure_arrivee",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure d'arrivée (check-in)"
                    ),
                ),
                (
                    "heure_depart",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="heure de départ (check-out)",
                    ),
                ),
                (
                    "equipements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste parmi apps.locations.services.EQUIPEMENTS_ETABLISSEMENT_LIBELLES.",
                        verbose_name="équipements de l'établissement",
                    ),
                ),
                (
                    "petit_dejeuner",
                    models.CharField(
                        choices=[
                            ("inclus", "Inclus"),
                            ("en_option", "En option"),
                            ("non", "Non proposé"),
                        ],
                        default="non",
                        max_length=10,
                        verbose_name="petit-déjeuner",
                    ),
                ),
                (
                    "prix_petit_dejeuner",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix du petit-déjeuner (FCFA)",
                    ),
                ),
                (
                    "politique_annulation",
                    models.TextField(blank=True, verbose_name="politique d'annulation"),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Caution, pièces exigées…",
                        verbose_name="conditions",
                    ),
                ),
                (
                    "modifie_par_role",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="modifié par (rôle)"
                    ),
                ),
                (
                    "modifie_par_nom",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="modifié par (nom)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "partenaire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_etablissement",
                        to="users.profilpartenaire",
                        verbose_name="partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche établissement",
                "verbose_name_plural": "fiches établissement",
            },
        ),
    ]
