# Generated by Django 5.0.6 on 2026-08-13 08:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_demandeur', models.CharField(blank=True, default='', help_text='client / partenaire — pour analytics seulement.', max_length=12)),
                ('a_quartier', models.CharField(max_length=150, verbose_name='A - quartier')),
                ('a_nom_contact', models.CharField(max_length=150, verbose_name='A - nom contact')),
                ('a_telephone_contact', models.CharField(max_length=20, verbose_name='A - telephone')),
                ('a_position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='A - GPS')),
                ('b_quartier', models.CharField(max_length=150, verbose_name='B - quartier')),
                ('b_nom_contact', models.CharField(max_length=150, verbose_name='B - nom contact')),
                ('b_telephone_contact', models.CharField(max_length=20, verbose_name='B - telephone')),
                ('b_position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='B - GPS')),
                ('description_colis', models.CharField(blank=True, default='', help_text='Repere pour le livreur (ex: pain, pagne, chaussures).', max_length=200)),
                ('prix', models.PositiveIntegerField(default=0, help_text='Prix en FCFA (fixe au depart, evolutif).')),
                ('statut', models.CharField(choices=[('demandee', 'Demandee'), ('assignee', 'Assignee a un livreur'), ('acceptee', 'Acceptee'), ('vers_a', 'En route vers le retrait'), ('colis_pris', 'Colis recupere'), ('vers_b', 'En route vers la livraison'), ('livree', 'Livree'), ('refusee', 'Refusee par le livreur'), ('annulee', 'Annulee')], default='demandee', max_length=12)),
                ('raison_refus', models.CharField(blank=True, default='', max_length=200)),
                ('assignee_le', models.DateTimeField(blank=True, null=True)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True)),
                ('colis_pris_le', models.DateTimeField(blank=True, null=True)),
                ('livree_le', models.DateTimeField(blank=True, null=True)),
                ('annulee_le', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_demandees', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
