# Generated by Django 5.0.6 on 2026-08-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('livraison', '0001_initial'),
        ('livreurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='livreurs.livreur', verbose_name='livreur assigne'),
        ),
        migrations.AddField(
            model_name='course',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='geo.departement', verbose_name='ville'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['statut', '-cree_le'], name='livraison_c_statut_966a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['livreur', 'statut'], name='livraison_c_livreur_23d9b0_idx'),
        ),
    ]
