# Generated by Django 5.0.6 on 2026-08-14 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_course_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('prix_course', models.PositiveIntegerField(default=500, help_text='Prix unique applique a toute course, en FCFA.', verbose_name="prix d'une course (FCFA)")),
            ],
            options={
                'verbose_name': 'parametres livraison',
                'verbose_name_plural': 'parametres livraison',
            },
        ),
    ]
