# Generated by Django 5.0.6 on 2026-08-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_parametreslivraison'),
        ('orders', '0004_commande_localisation_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='orders.commande', verbose_name='commande liee'),
        ),
    ]
