# Generated by Django 5.0.6 on 2026-08-15 18:13

import apps.core.images
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_course_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconeMotard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(help_text="Libelle pour reconnaitre l'icone (ex: motard rouge).", max_length=100, verbose_name='nom')),
                ('role', models.CharField(choices=[('standard', 'Standard (course en cours)'), ('terminee', 'Livraison terminee')], default='standard', help_text='Standard = pendant la course ; Terminee = a la livraison.', max_length=12, verbose_name='role')),
                ('image', models.ImageField(help_text='PNG transparent recommande.', upload_to='carte/motards/', verbose_name='image (PNG)')),
                ('est_active', models.BooleanField(default=False, help_text="Une seule active par role : l'app utilise celle-ci.", verbose_name='active')),
            ],
            options={
                'verbose_name': 'icone motard',
                'verbose_name_plural': 'icones motard',
                'ordering': ['role', '-est_active', '-cree_le'],
            },
            bases=(apps.core.images.ImagesOptimiseesMixin, models.Model),
        ),
    ]
