# Generated by Django 5.0.6 on 2026-08-20 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_quartier_quartier_unique_quartier_departement'),
        ('livraison', '0006_iconemotard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Permet de désactiver un bureau sans supprimer le compte.', verbose_name='actif')),
                ('nom_bureau', models.CharField(blank=True, default='', help_text='Nom lisible du bureau, ex. « Bureau TeneLivr Ferké ».', max_length=150, verbose_name='nom du bureau')),
                ('departement', models.ForeignKey(blank=True, help_text='Rempli pour un gestionnaire (sa ville). Laisser vide pour un superviseur (voit toutes les villes).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestionnaires_livraison', to='geo.departement', verbose_name='ville de rattachement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livraison', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
            ],
            options={
                'verbose_name': 'profil de livraison',
                'verbose_name_plural': 'profils de livraison',
            },
        ),
    ]
