# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('ouvert', models.BooleanField(default=True, verbose_name='ouvert ce jour')),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name="heure d'ouverture")),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='heure de fermeture')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='début de pause')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='fin de pause')),
                ('note', models.CharField(blank=True, help_text='Ex: "Horaires Ramadan", "Fermé en cas de pluie"…', max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['partenaire', 'jour_semaine'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basique', 'Basique'), ('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP')], help_text='Identifiant technique du palier (basique, standard, premium, vip).', max_length=20, verbose_name='code interne')),
                ('libelle', models.CharField(help_text='Nom affiché dans l\'app (ex: "Premium 30 jours").', max_length=50, verbose_name='libellé')),
                ('description', models.TextField(blank=True, help_text='Détails du plan, avantages, à destination des commerçants.', verbose_name='description')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('duree_jours', models.IntegerField(default=30, help_text='Durée de validité. 1 = 24h, 7 = 1 semaine, 30 = 1 mois, 365 = 1 an. -1 pour illimité.', verbose_name='durée (en jours)')),
                ('nb_articles_max', models.IntegerField(default=10, help_text='-1 pour illimité.', verbose_name="nombre max d'articles")),
                ('nb_photos_par_article', models.IntegerField(default=1, verbose_name='photos par article')),
                ('peut_publier_video', models.BooleanField(default=False, verbose_name='peut publier des vidéos')),
                ('peut_etre_mis_en_avant', models.BooleanField(default=False, help_text="Le commerçant peut apparaître dans les carrousels d'accueil.", verbose_name='éligible mise en avant')),
                ('boost_visibilite', models.IntegerField(default=0, help_text='Multiplicateur appliqué au tri (0 = aucun, plus = remonte).', verbose_name='boost de visibilité')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour retirer le plan de la liste des choix possibles.', verbose_name='plan actif')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='ProfilPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_partenaire', models.CharField(choices=[('commercant', 'Commerçant'), ('pharmacien', 'Pharmacien'), ('boulanger', 'Boulanger'), ('restaurateur', 'Restaurateur'), ('couturier', 'Couturier / Couturière'), ('menuisier', 'Menuisier'), ('plombier', 'Plombier'), ('electricien', 'Électricien'), ('macon', 'Maçon'), ('coiffeur', 'Coiffeur / Coiffeuse'), ('libraire', 'Libraire'), ('hotelier', 'Hôtelier'), ('mecanicien', 'Mécanicien'), ('loueur_maison', 'Loueur de maison'), ('loueur_voiture', 'Loueur de voiture'), ('autre', 'Autre')], default='commercant', help_text="Désigne l'appellation du partenaire (commerçant, pharmacien, coiffeur, etc.).", max_length=20, verbose_name='type de partenaire')),
                ('nom_commerce', models.CharField(max_length=150, verbose_name="nom de l'enseigne")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/', verbose_name='logo')),
                ('photo_couverture', models.ImageField(blank=True, null=True, upload_to='partenaires/couvertures/', verbose_name='photo de couverture')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='quartier')),
                ('secteur', models.CharField(blank=True, max_length=100, verbose_name='secteur')),
                ('ville', models.CharField(default='Ferkessédougou', max_length=100, verbose_name='ville')),
                ('description_acces', models.TextField(blank=True, help_text='Indications complémentaires pour les clients (ex: "à côté du marché central").', verbose_name='comment trouver le partenaire')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Coordonnées GPS (optionnel, peut être ajouté plus tard).', null=True, srid=4326, verbose_name='position GPS')),
                ('telephone_pro', models.CharField(blank=True, max_length=20, verbose_name='téléphone professionnel')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='numéro WhatsApp')),
                ('email_pro', models.EmailField(blank=True, max_length=254, verbose_name='email professionnel')),
                ('abonnement_debut', models.DateField(blank=True, null=True, verbose_name="début de l'abonnement")),
                ('abonnement_fin', models.DateField(blank=True, help_text='Date au-delà de laquelle le plan repasse en Basique.', null=True, verbose_name="fin de l'abonnement")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('banni', 'Banni')], default='en_attente', max_length=20, verbose_name='statut')),
                ('est_visible', models.BooleanField(default=True, help_text='Décocher pour masquer temporairement le partenaire sans le supprimer.', verbose_name="visible dans l'app")),
                ('visibilite_jusquau', models.DateField(blank=True, help_text='Si renseigné, le partenaire est auto-masqué après cette date.', null=True, verbose_name="visibilité jusqu'au")),
                ('paye_publicite', models.BooleanField(default=False, verbose_name='a payé la publicité')),
                ('pub_active_jusquau', models.DateField(blank=True, null=True, verbose_name="publicité active jusqu'au")),
                ('score_priorite', models.IntegerField(default=0, help_text="Boost manuel : plus c'est haut, plus le partenaire remonte dans les listes.", verbose_name='score de priorité')),
                ('badge_certifie', models.BooleanField(default=False, verbose_name='badge certifié')),
                ('taxes_communales_ok', models.BooleanField(default=False, verbose_name='taxes communales à jour')),
                ('date_verif_taxes', models.DateField(blank=True, null=True, verbose_name='date de vérification des taxes')),
                ('est_faveur', models.BooleanField(default=False, help_text="Le partenaire bénéficie d'avantages offerts sans paiement.", verbose_name='en faveur')),
                ('faveur_motif', models.TextField(blank=True, help_text='Ex: "Partenariat", "Structure interne", "Bon client historique"…', verbose_name='motif de la faveur')),
                ('notes_admin', models.TextField(blank=True, help_text='Commentaires non visibles par le partenaire.', verbose_name='notes internes admin')),
                ('derniere_verif', models.DateField(blank=True, null=True, verbose_name='dernière vérification')),
                ('source_inscription', models.CharField(choices=[('self', "Auto-inscription via l'app"), ('kobo', 'Import Kobo Toolbox'), ('admin', 'Créé par un admin')], default='self', max_length=20, verbose_name="source d'inscription")),
                ('id_kobo', models.CharField(blank=True, help_text='Référence du formulaire Kobo Toolbox pour réconciliation.', max_length=100, verbose_name='ID Kobo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'profil partenaire',
                'verbose_name_plural': 'profils partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(help_text='Numéro de téléphone au format international (+225...)', max_length=20, unique=True, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('client', 'Client'), ('partenaire', 'Partenaire'), ('livreur', 'Livreur'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='rôle')),
                ('est_verifie', models.BooleanField(default=False, help_text='Le téléphone a été vérifié via un code OTP par SMS.', verbose_name='téléphone vérifié')),
                ('token_fcm', models.CharField(blank=True, help_text='Token Firebase Cloud Messaging pour les notifications push.', max_length=255, null=True, verbose_name='token FCM')),
                ('langue_preferee', models.CharField(default='fr', max_length=10, verbose_name='langue préférée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdresseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: "Maison", "Bureau", "Chez maman"…', max_length=50, verbose_name='libellé')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('description_acces', models.TextField(blank=True, help_text='Ex: "Porte verte, 1er étage, à droite de la pharmacie".', verbose_name="comment trouver l'adresse")),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='position GPS')),
                ('est_principale', models.BooleanField(default=False, help_text="L'adresse principale est sélectionnée par défaut au moment de commander.", verbose_name='adresse principale')),
                ('est_active', models.BooleanField(default=True, verbose_name='adresse active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'adresse client',
                'verbose_name_plural': 'adresses clients',
                'ordering': ['user', '-est_principale', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='planabonnement',
            constraint=models.UniqueConstraint(fields=('code', 'duree_jours'), name='unique_plan_code_duree'),
        ),
        migrations.AddField(
            model_name='profilpartenaire',
            name='faveur_accordee_par',
            field=models.ForeignKey(blank=True, help_text='Admin qui a accordé la faveur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faveurs_accordees', to=settings.AUTH_USER_MODEL, verbose_name='faveur accordée par'),
        ),
        migrations.AddField(
            model_name='profilpartenaire',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partenaires', to='users.planabonnement', verbose_name="plan d'abonnement"),
        ),
        migrations.AddField(
            model_name='profilpartenaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_partenaire', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur'),
        ),
        migrations.AddField(
            model_name='horaireouverture',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='users.profilpartenaire', verbose_name='partenaire'),
        ),
        migrations.AddIndex(
            model_name='profilpartenaire',
            index=models.Index(fields=['statut'], name='users_profi_statut_d4e52d_idx'),
        ),
        migrations.AddIndex(
            model_name='profilpartenaire',
            index=models.Index(fields=['ville'], name='users_profi_ville_4d547d_idx'),
        ),
        migrations.AddIndex(
            model_name='profilpartenaire',
            index=models.Index(fields=['type_partenaire'], name='users_profi_type_pa_ece52e_idx'),
        ),
        migrations.AddConstraint(
            model_name='horaireouverture',
            constraint=models.UniqueConstraint(fields=('partenaire', 'jour_semaine'), name='unique_horaire_par_jour'),
        ),
    ]
