# Generated by Django 5.0.6 on 2026-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basique', 'Basique'), ('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP')], help_text='Identifiant technique du palier (basique, standard, premium, vip).', max_length=20, verbose_name='code interne')),
                ('libelle', models.CharField(help_text='Nom affiché dans l\'app (ex: "Premium 30 jours").', max_length=50, verbose_name='libellé')),
                ('description', models.TextField(blank=True, help_text='Détails du plan, avantages, à destination des commerçants.', verbose_name='description')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('duree_jours', models.IntegerField(default=30, help_text='Durée de validité. 1 = 24h, 7 = 1 semaine, 30 = 1 mois, 365 = 1 an. -1 pour illimité.', verbose_name='durée (en jours)')),
                ('nb_articles_max', models.IntegerField(default=10, help_text='-1 pour illimité.', verbose_name="nombre max d'articles")),
                ('nb_photos_par_article', models.IntegerField(default=1, verbose_name='photos par article')),
                ('peut_publier_video', models.BooleanField(default=False, verbose_name='peut publier des vidéos')),
                ('peut_etre_mis_en_avant', models.BooleanField(default=False, help_text="Le commerçant peut apparaître dans les carrousels d'accueil.", verbose_name='éligible mise en avant')),
                ('boost_visibilite', models.IntegerField(default=0, help_text='Multiplicateur appliqué au tri (0 = aucun, plus = remonte).', verbose_name='boost de visibilité')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour retirer le plan de la liste des choix possibles.', verbose_name='plan actif')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.AddConstraint(
            model_name='planabonnement',
            constraint=models.UniqueConstraint(fields=('code', 'duree_jours'), name='unique_plan_code_duree'),
        ),
    ]
