# Generated by Django 5.0.6 on 2026-06-15 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAppareil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('appareil_nom', models.CharField(blank=True, max_length=150, verbose_name="nom de l'appareil")),
                ('appareil_id', models.CharField(blank=True, help_text='Identifiant unique fourni par le client (device id).', max_length=255, verbose_name='identifiant appareil')),
                ('plateforme', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('autre', 'Autre')], default='autre', max_length=10, verbose_name='plateforme')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('derniere_activite_le', models.DateTimeField(auto_now=True, verbose_name='dernière activité')),
                ('est_active', models.BooleanField(default=True, verbose_name='session active')),
                ('revoque_le', models.DateTimeField(blank=True, null=True, verbose_name='révoquée le')),
                ('revoque_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_revoquees', to=settings.AUTH_USER_MODEL, verbose_name='révoquée par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_appareils', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'session appareil',
                'verbose_name_plural': 'sessions appareils',
                'ordering': ['-derniere_activite_le'],
                'indexes': [models.Index(fields=['user', 'est_active'], name='users_sessi_user_id_805c18_idx')],
            },
        ),
    ]
