# Generated by Django 5.0.6 on 2026-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sessionappareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpartenaire',
            name='nb_vues',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de vues de la vitrine'),
        ),
    ]
