# Generated by Django 5.0.6 on 2026-06-11 12:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_planabonnement_planabonnement_unique_plan_code_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commerce', models.CharField(max_length=150, verbose_name='nom du commerce')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='commercants/logos/', verbose_name='logo')),
                ('photo_couverture', models.ImageField(blank=True, null=True, upload_to='commercants/couvertures/', verbose_name='photo de couverture')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='quartier')),
                ('secteur', models.CharField(blank=True, max_length=100, verbose_name='secteur')),
                ('ville', models.CharField(default='Ferkessédougou', max_length=100, verbose_name='ville')),
                ('description_acces', models.TextField(blank=True, help_text='Indications complémentaires pour les clients (ex: "à côté du marché central").', verbose_name='comment trouver le commerce')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Coordonnées GPS du commerce (optionnel, peut être ajouté plus tard).', null=True, srid=4326, verbose_name='position GPS')),
                ('telephone_pro', models.CharField(blank=True, max_length=20, verbose_name='téléphone professionnel')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='numéro WhatsApp')),
                ('email_pro', models.EmailField(blank=True, max_length=254, verbose_name='email professionnel')),
                ('abonnement_debut', models.DateField(blank=True, null=True, verbose_name="début de l'abonnement")),
                ('abonnement_fin', models.DateField(blank=True, help_text='Date au-delà de laquelle le plan repasse en Basique.', null=True, verbose_name="fin de l'abonnement")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('banni', 'Banni')], default='en_attente', max_length=20, verbose_name='statut')),
                ('est_visible', models.BooleanField(default=True, help_text='Décocher pour masquer temporairement le commerce sans le supprimer.', verbose_name="visible dans l'app")),
                ('visibilite_jusquau', models.DateField(blank=True, help_text='Si renseigné, le commerce est auto-masqué après cette date.', null=True, verbose_name="visibilité jusqu'au")),
                ('paye_publicite', models.BooleanField(default=False, verbose_name='a payé la publicité')),
                ('pub_active_jusquau', models.DateField(blank=True, null=True, verbose_name="publicité active jusqu'au")),
                ('score_priorite', models.IntegerField(default=0, help_text="Boost manuel : plus c'est haut, plus le commerce remonte dans les listes.", verbose_name='score de priorité')),
                ('badge_certifie', models.BooleanField(default=False, verbose_name='badge certifié')),
                ('taxes_communales_ok', models.BooleanField(default=False, verbose_name='taxes communales à jour')),
                ('date_verif_taxes', models.DateField(blank=True, null=True, verbose_name='date de vérification des taxes')),
                ('est_faveur', models.BooleanField(default=False, help_text="Le commerçant bénéficie d'avantages offerts sans paiement.", verbose_name='en faveur')),
                ('faveur_motif', models.TextField(blank=True, help_text='Ex: "Partenariat", "Structure interne", "Bon client historique"…', verbose_name='motif de la faveur')),
                ('notes_admin', models.TextField(blank=True, help_text='Commentaires non visibles par le commerçant.', verbose_name='notes internes admin')),
                ('derniere_verif', models.DateField(blank=True, null=True, verbose_name='dernière vérification')),
                ('source_inscription', models.CharField(choices=[('self', "Auto-inscription via l'app"), ('kobo', 'Import Kobo Toolbox'), ('admin', 'Créé par un admin')], default='self', max_length=20, verbose_name="source d'inscription")),
                ('id_kobo', models.CharField(blank=True, help_text='Référence du formulaire Kobo Toolbox pour réconciliation.', max_length=100, verbose_name='ID Kobo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('faveur_accordee_par', models.ForeignKey(blank=True, help_text='Admin qui a accordé la faveur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faveurs_accordees', to=settings.AUTH_USER_MODEL, verbose_name='faveur accordée par')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercants', to='users.planabonnement', verbose_name="plan d'abonnement")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_commercant', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
            ],
            options={
                'verbose_name': 'profil commerçant',
                'verbose_name_plural': 'profils commerçants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut'], name='users_profi_statut_2b0228_idx'), models.Index(fields=['ville'], name='users_profi_ville_595374_idx')],
            },
        ),
    ]
