# Generated by Django 5.0.6 on 2026-07-31 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('users', '0003_profilpartenaire_nb_vues'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpartenaire',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département du commerce. Remplace progressivement le champ texte « ville ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partenaires', to='geo.departement', verbose_name='département'),
        ),
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='geo.departement', verbose_name='departement'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('non_precise', 'Préfère ne pas préciser')], max_length=12, verbose_name='sexe'),
        ),
        migrations.AddField(
            model_name='user',
            name='tranche_age',
            field=models.CharField(blank=True, choices=[('moins_18', 'Moins de 18 ans'), ('18_24', '18 - 24 ans'), ('25_34', '25 - 34 ans'), ('35_44', '35 - 44 ans'), ('45_54', '45 - 54 ans'), ('55_plus', '55 ans et plus')], max_length=10, verbose_name='tranche age'),
        ),
    ]
