# Generated by Django 5.0.6 on 2026-06-11 12:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilcommercant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: "Maison", "Bureau", "Chez maman"…', max_length=50, verbose_name='libellé')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('description_acces', models.TextField(blank=True, help_text='Ex: "Porte verte, 1er étage, à droite de la pharmacie".', verbose_name="comment trouver l'adresse")),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='position GPS')),
                ('est_principale', models.BooleanField(default=False, help_text="L'adresse principale est sélectionnée par défaut au moment de commander.", verbose_name='adresse principale')),
                ('est_active', models.BooleanField(default=True, verbose_name='adresse active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'adresse client',
                'verbose_name_plural': 'adresses clients',
                'ordering': ['user', '-est_principale', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('ouvert', models.BooleanField(default=True, verbose_name='ouvert ce jour')),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name="heure d'ouverture")),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='heure de fermeture')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='début de pause')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='fin de pause')),
                ('note', models.CharField(blank=True, help_text='Ex: "Horaires Ramadan", "Fermé en cas de pluie"…', max_length=200, verbose_name='note')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='users.profilcommercant', verbose_name='commerçant')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['commercant', 'jour_semaine'],
            },
        ),
        migrations.AddConstraint(
            model_name='horaireouverture',
            constraint=models.UniqueConstraint(fields=('commercant', 'jour_semaine'), name='unique_horaire_par_jour'),
        ),
    ]
