# Generated by Django 5.0.6 on 2026-08-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilpartenaire_departement_user_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planabonnement',
            name='nb_videos_par_article',
            field=models.IntegerField(default=0, help_text='0 = aucune vidéo autorisée pour ce plan.', verbose_name='vidéos par article'),
        ),
    ]
