# Generated by Django 5.0.6 on 2026-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_planabonnement_nb_videos_par_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='planabonnement',
            name='portee',
            field=models.CharField(choices=[('departement', 'Departement seulement'), ('region', 'Toute la region'), ('district', 'Tout le district')], default='departement', help_text="Jusqu'ou les partenaires de ce plan sont visibles : leur departement, leur region, ou tout le district.", max_length=12, verbose_name='portee geographique'),
        ),
    ]
