# Generated by Django 5.0.6 on 2026-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_planabonnement_portee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='est_banni',
            field=models.BooleanField(default=False, help_text='Bannissement = suspension permanente.', verbose_name='banni'),
        ),
        migrations.AddField(
            model_name='user',
            name='est_supprime',
            field=models.BooleanField(default=False, help_text='Suppression douce : compte désactivé mais récupérable.', verbose_name='supprimé (soft)'),
        ),
        migrations.AddField(
            model_name='user',
            name='est_suspendu',
            field=models.BooleanField(default=False, verbose_name='suspendu'),
        ),
        migrations.AddField(
            model_name='user',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='supprimé le'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspendu_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suspendu le'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_motif',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif de suspension'),
        ),
    ]
