# Generated by Django 5.0.6 on 2026-08-05 13:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_est_banni_user_est_supprime_user_est_suspendu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
            ],
            options={
                'verbose_name': 'livreur',
                'verbose_name_plural': 'Livreurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'Partenaires',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
