# Generated by Django 5.0.6 on 2026-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_administrateur_client_livreur_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpartenaire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('banni', 'Banni'), ('rejete', 'Demande rejetée')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
