# Generated by Django 5.0.6 on 2026-08-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profilpartenaire_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
        migrations.DeleteModel(
            name='Partenaire',
        ),
    ]
