# Generated by Django 5.0.6 on 2026-08-06 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_administrateur_delete_client_delete_livreur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroVerifie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('telephone', models.CharField(db_index=True, help_text='Numéro déjà vérifié, au format international (+225...).', max_length=20, unique=True, verbose_name='téléphone')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('source', models.CharField(choices=[('otp', 'OTP validé par SMS'), ('admin', 'Créé par un admin'), ('demarcheur', 'Pré-saisi par un démarcheur'), ('migration', 'Compte préexistant migré')], default='otp', max_length=15, verbose_name='source de la vérification')),
            ],
            options={
                'verbose_name': 'numéro vérifié',
                'verbose_name_plural': 'numéros vérifiés',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pin_par_defaut',
            field=models.BooleanField(default=False, help_text='True si le PIN est encore celui fourni à la création (compte créé par un admin) et doit être changé à la 1re connexion.', verbose_name='PIN par défaut à changer'),
        ),
    ]
