# Generated by Django 5.0.6 on 2026-08-06 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_numeroverifie_user_pin_par_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('telephone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('code', models.CharField(max_length=4, verbose_name='code')),
                ('but', models.CharField(choices=[('inscription', 'Inscription'), ('reinit_pin', 'Réinitialisation du PIN')], default='inscription', max_length=20, verbose_name='but')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('tentatives', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('est_utilise', models.BooleanField(default=False, verbose_name='déjà utilisé')),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['telephone', 'est_utilise'], name='users_codeo_telepho_89c78e_idx')],
            },
        ),
    ]
