# Generated by Django 5.0.6 on 2026-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_codeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeotp',
            name='pin_consomme',
            field=models.BooleanField(default=False, verbose_name='validation consommée pour le PIN'),
        ),
        migrations.AddField(
            model_name='codeotp',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validé le'),
        ),
    ]
