# Generated by Django 5.0.6 on 2026-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_codeotp_pin_consomme_codeotp_valide_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpartenaire',
            name='ville',
            field=models.CharField(default='Ferké', max_length=100, verbose_name='ville'),
        ),
    ]
