# Generated by Django 5.0.6 on 2026-08-16 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profilpartenaire_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSecurite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('pins_interdits', models.JSONField(blank=True, default=list, help_text='Liste de codes PIN a 4 chiffres refuses (ex: ["0000", "1111", "1234"]).', verbose_name='PIN interdits')),
                ('bloquer_suites', models.BooleanField(default=True, help_text='Refuse les suites croissantes ou decroissantes (1234, 2345, 4321, 9876...).', verbose_name='bloquer les suites')),
            ],
            options={
                'verbose_name': 'parametres securite',
                'verbose_name_plural': 'parametres securite',
            },
        ),
    ]
