# Generated by Django 5.0.6 on 2026-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_teneli_livraison_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('partenaire', 'Partenaire'), ('livreur', 'Livreur'), ('admin', 'Administrateur'), ('gestionnaire_livraison', 'Gestionnaire de livraison'), ('superviseur_livraison', 'Superviseur de livraison'), ('coordonnateur_livraison', 'Coordonnateur de livraison')], default='client', max_length=30, verbose_name='rôle'),
        ),
    ]
