# Generated by Django 5.0.6 on 2026-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_migrer_superviseurs_nationaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroverifie',
            name='source',
            field=models.CharField(choices=[('otp', 'OTP validé par SMS'), ('firebase', 'Vérifié via Firebase Phone Auth'), ('admin', 'Créé par un admin'), ('demarcheur', 'Pré-saisi par un démarcheur'), ('migration', 'Compte préexistant migré')], default='otp', max_length=15, verbose_name='source de la vérification'),
        ),
    ]
