# Generated by Django 5.0.6 on 2026-10-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_departement_cree_le_departement_modifie_le_and_more'),
        ('users', '0019_alter_numeroverifie_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpartenaire',
            name='localite',
            field=models.ForeignKey(blank=True, help_text='Choisie dans la géographie. Synchronise le champ texte « ville ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partenaires', to='geo.localite', verbose_name='localité'),
        ),
        migrations.AddField(
            model_name='profilpartenaire',
            name='quartier_geo',
            field=models.ForeignKey(blank=True, help_text='Choisi dans la géographie. Synchronise le champ texte « quartier ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partenaires', to='geo.quartier', verbose_name='quartier (géographie)'),
        ),
    ]
