# Generated by Django 5.0.6 on 2026-10-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_geo_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpartenaire',
            name='position_modifiee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='position modifiée le'),
        ),
        migrations.AddField(
            model_name='profilpartenaire',
            name='position_modifiee_par_role',
            field=models.CharField(blank=True, help_text="'admin' ou 'partenaire'.", max_length=12, verbose_name='position modifiée par (rôle)'),
        ),
    ]
