"""Routes du module restaurants (préfixées /api/v1/restaurants/)."""
from django.urls import path

from .views_admin_liste import RestaurantsAdminListeView
from .views_carte import (
    AdminGroupeOptionCarteDetailView, AdminGroupesOptionsCarteView,
    AdminOptionCarteDetailView, AdminOptionsCarteView,
    AdminPlatCarteDetailView, AdminPlatEpuiseView, AdminPlatImageDetailView,
    AdminPlatImagesView, AdminPlatsCarteView,
    AdminSectionCarteDetailView, AdminSectionsCarteView,
    AdminVarianteCarteDetailView, AdminVariantesCarteView,
    MonGroupeOptionCarteDetailView, MonGroupesOptionsCarteView,
    MonOptionCarteDetailView, MonOptionsCarteView,
    MonPlatCarteDetailView, MonPlatEpuiseView, MonPlatImageDetailView,
    MonPlatImagesView, MonPlatsCarteView,
    MonSectionCarteDetailView, MonSectionsCarteView,
    MonVarianteCarteDetailView, MonVariantesCarteView,
)
from .views_prive import (
    AdminCopierSemaineView, AdminDupliquerMenuView, AdminFicheRestaurantView,
    AdminHorairesRestaurantView, AdminLigneMenuDetailView, AdminLignesMenuView,
    AdminMenuRestaurantDetailView, AdminMenusRestaurantView,
    AdminTelephoneRestaurantDetailView, AdminTelephonesRestaurantView,
    MonCopierSemaineView, MonDupliquerMenuView, MonFicheRestaurantView,
    MonHorairesRestaurantView, MonLigneMenuDetailView, MonLignesMenuView,
    MonMenuRestaurantDetailView, MonMenusRestaurantView,
    MonTelephoneRestaurantDetailView, MonTelephonesRestaurantView,
)
from .views_public import MenusDuJourView, RestaurantDetailPublicView, RestaurantsListeView

app_name = 'restaurants'

urlpatterns = [
    # ── Lecture publique ──────────────────────────────────────────────
    path('menus-du-jour/', MenusDuJourView.as_view(), name='menus-du-jour'),
    path('', RestaurantsListeView.as_view(), name='liste'),
    path('<int:pk>/', RestaurantDetailPublicView.as_view(), name='detail'),

    # ── Restaurateur (son propre restaurant) ──────────────────────────
    path('mon-restaurant/fiche/', MonFicheRestaurantView.as_view(), name='mon-fiche'),
    path('mon-restaurant/horaires/', MonHorairesRestaurantView.as_view(), name='mon-horaires'),
    path('mon-restaurant/telephones/', MonTelephonesRestaurantView.as_view(), name='mon-telephones'),
    path('mon-restaurant/telephones/<int:pk>/', MonTelephoneRestaurantDetailView.as_view(),
         name='mon-telephone-detail'),
    path('mon-restaurant/menus/', MonMenusRestaurantView.as_view(), name='mon-menus'),
    path('mon-restaurant/menus/copier-semaine/', MonCopierSemaineView.as_view(),
         name='mon-copier-semaine'),
    path('mon-restaurant/menus/<int:pk>/', MonMenuRestaurantDetailView.as_view(),
         name='mon-menu-detail'),
    path('mon-restaurant/menus/<int:pk>/dupliquer/', MonDupliquerMenuView.as_view(),
         name='mon-menu-dupliquer'),
    path('mon-restaurant/lignes-menu/', MonLignesMenuView.as_view(), name='mon-lignes-menu'),
    path('mon-restaurant/lignes-menu/<int:pk>/', MonLigneMenuDetailView.as_view(),
         name='mon-ligne-menu-detail'),

    # ── Restaurateur : carte ───────────────────────────────────────────
    path('mon-restaurant/carte/sections/', MonSectionsCarteView.as_view(), name='mon-carte-sections'),
    path('mon-restaurant/carte/sections/<int:pk>/', MonSectionCarteDetailView.as_view(),
         name='mon-carte-section-detail'),
    path('mon-restaurant/carte/plats/', MonPlatsCarteView.as_view(), name='mon-carte-plats'),
    path('mon-restaurant/carte/plats/<int:pk>/', MonPlatCarteDetailView.as_view(),
         name='mon-carte-plat-detail'),
    path('mon-restaurant/carte/plats/<int:pk>/epuise/', MonPlatEpuiseView.as_view(),
         name='mon-carte-plat-epuise'),
    path('mon-restaurant/carte/plats/<int:plat_id>/images/', MonPlatImagesView.as_view(),
         name='mon-carte-plat-images'),
    path('mon-restaurant/carte/plats/<int:plat_id>/images/<int:pk>/',
         MonPlatImageDetailView.as_view(), name='mon-carte-plat-image-detail'),
    path('mon-restaurant/carte/variantes/', MonVariantesCarteView.as_view(),
         name='mon-carte-variantes'),
    path('mon-restaurant/carte/variantes/<int:pk>/', MonVarianteCarteDetailView.as_view(),
         name='mon-carte-variante-detail'),
    path('mon-restaurant/carte/groupes-options/', MonGroupesOptionsCarteView.as_view(),
         name='mon-carte-groupes-options'),
    path('mon-restaurant/carte/groupes-options/<int:pk>/',
         MonGroupeOptionCarteDetailView.as_view(), name='mon-carte-groupe-option-detail'),
    path('mon-restaurant/carte/options/', MonOptionsCarteView.as_view(), name='mon-carte-options'),
    path('mon-restaurant/carte/options/<int:pk>/', MonOptionCarteDetailView.as_view(),
         name='mon-carte-option-detail'),

    # ── Admin (à la place d'un restaurateur donné) ────────────────────
    path('admin/', RestaurantsAdminListeView.as_view(), name='admin-liste'),
    path('admin/<int:partenaire_id>/fiche/', AdminFicheRestaurantView.as_view(), name='admin-fiche'),
    path('admin/<int:partenaire_id>/horaires/', AdminHorairesRestaurantView.as_view(),
         name='admin-horaires'),
    path('admin/<int:partenaire_id>/telephones/', AdminTelephonesRestaurantView.as_view(),
         name='admin-telephones'),
    path('admin/<int:partenaire_id>/telephones/<int:pk>/',
         AdminTelephoneRestaurantDetailView.as_view(), name='admin-telephone-detail'),
    path('admin/<int:partenaire_id>/menus/', AdminMenusRestaurantView.as_view(), name='admin-menus'),
    path('admin/<int:partenaire_id>/menus/copier-semaine/', AdminCopierSemaineView.as_view(),
         name='admin-copier-semaine'),
    path('admin/<int:partenaire_id>/menus/<int:pk>/', AdminMenuRestaurantDetailView.as_view(),
         name='admin-menu-detail'),
    path('admin/<int:partenaire_id>/menus/<int:pk>/dupliquer/', AdminDupliquerMenuView.as_view(),
         name='admin-menu-dupliquer'),
    path('admin/<int:partenaire_id>/lignes-menu/', AdminLignesMenuView.as_view(),
         name='admin-lignes-menu'),
    path('admin/<int:partenaire_id>/lignes-menu/<int:pk>/', AdminLigneMenuDetailView.as_view(),
         name='admin-ligne-menu-detail'),

    # ── Admin : carte ──────────────────────────────────────────────────
    path('admin/<int:partenaire_id>/carte/sections/', AdminSectionsCarteView.as_view(),
         name='admin-carte-sections'),
    path('admin/<int:partenaire_id>/carte/sections/<int:pk>/',
         AdminSectionCarteDetailView.as_view(), name='admin-carte-section-detail'),
    path('admin/<int:partenaire_id>/carte/plats/', AdminPlatsCarteView.as_view(),
         name='admin-carte-plats'),
    path('admin/<int:partenaire_id>/carte/plats/<int:pk>/', AdminPlatCarteDetailView.as_view(),
         name='admin-carte-plat-detail'),
    path('admin/<int:partenaire_id>/carte/plats/<int:pk>/epuise/',
         AdminPlatEpuiseView.as_view(), name='admin-carte-plat-epuise'),
    path('admin/<int:partenaire_id>/carte/plats/<int:plat_id>/images/',
         AdminPlatImagesView.as_view(), name='admin-carte-plat-images'),
    path('admin/<int:partenaire_id>/carte/plats/<int:plat_id>/images/<int:pk>/',
         AdminPlatImageDetailView.as_view(), name='admin-carte-plat-image-detail'),
    path('admin/<int:partenaire_id>/carte/variantes/', AdminVariantesCarteView.as_view(),
         name='admin-carte-variantes'),
    path('admin/<int:partenaire_id>/carte/variantes/<int:pk>/',
         AdminVarianteCarteDetailView.as_view(), name='admin-carte-variante-detail'),
    path('admin/<int:partenaire_id>/carte/groupes-options/',
         AdminGroupesOptionsCarteView.as_view(), name='admin-carte-groupes-options'),
    path('admin/<int:partenaire_id>/carte/groupes-options/<int:pk>/',
         AdminGroupeOptionCarteDetailView.as_view(), name='admin-carte-groupe-option-detail'),
    path('admin/<int:partenaire_id>/carte/options/', AdminOptionsCarteView.as_view(),
         name='admin-carte-options'),
    path('admin/<int:partenaire_id>/carte/options/<int:pk>/',
         AdminOptionCarteDetailView.as_view(), name='admin-carte-option-detail'),
]
