# Generated by Django 5.0.6 on 2026-08-13 08:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto (local)'), ('voiture', 'Voiture (inter-regions)')], default='moto', max_length=10)),
                ('statut', models.CharField(choices=[('en_ligne', 'En ligne'), ('hors_ligne', 'Hors ligne')], default='hors_ligne', max_length=12)),
                ('source_position', models.CharField(choices=[('telephone', 'Telephone (app livreur)'), ('transpondeur', 'Transpondeur (boitier)')], default='telephone', help_text="D'ou vient la position : bascule telephone <-> transpondeur.", max_length=12)),
                ('transpondeur_id', models.CharField(blank=True, default='', help_text='Identifiant materiel du transpondeur, si source = transpondeur.', max_length=100)),
                ('immatriculation', models.CharField(blank=True, default='', max_length=30)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='derniere position GPS')),
                ('position_maj_le', models.DateTimeField(blank=True, null=True, verbose_name='position mise a jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livreurs', to='geo.departement', verbose_name='ville de rattachement')),
            ],
            options={
                'verbose_name': 'livreur',
                'verbose_name_plural': 'livreurs',
            },
        ),
    ]
