# Generated by Django 5.0.6 on 2026-08-04 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cible_identifiant', models.CharField(blank=True, help_text='Téléphone/identifiant conservé en clair (surtout si la cible est supprimée définitivement).', max_length=150, verbose_name='identifiant de la cible')),
                ('cible_role', models.CharField(blank=True, max_length=20, verbose_name='rôle de la cible')),
                ('action', models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive')], max_length=20, verbose_name='action')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_moderation', to=settings.AUTH_USER_MODEL, verbose_name='acteur (super-admin)')),
                ('cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations_subies', to=settings.AUTH_USER_MODEL, verbose_name='cible')),
            ],
            options={
                'verbose_name': 'entrée de journal de modération',
                'verbose_name_plural': 'journal de modération',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['cible', 'cree_le'], name='administrat_cible_i_89fd6d_idx'), models.Index(fields=['action', 'cree_le'], name='administrat_action_41e8c9_idx')],
            },
        ),
    ]
