# Generated by Django 5.0.6 on 2026-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)')], max_length=20, verbose_name='action'),
        ),
    ]
