# Generated by Django 5.0.6 on 2026-08-05 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_journalmoderation_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('suspendre_client', models.BooleanField(default=False, verbose_name='suspendre — clients')),
                ('suspendre_partenaire', models.BooleanField(default=False, verbose_name='suspendre — partenaires')),
                ('suspendre_admin', models.BooleanField(default=False, verbose_name='suspendre — admins')),
                ('reactiver_client', models.BooleanField(default=False, verbose_name='réactiver — clients')),
                ('reactiver_partenaire', models.BooleanField(default=False, verbose_name='réactiver — partenaires')),
                ('reactiver_admin', models.BooleanField(default=False, verbose_name='réactiver — admins')),
                ('bannir_client', models.BooleanField(default=False, verbose_name='bannir — clients')),
                ('bannir_partenaire', models.BooleanField(default=False, verbose_name='bannir — partenaires')),
                ('bannir_admin', models.BooleanField(default=False, verbose_name='bannir — admins')),
                ('supprimer_soft_client', models.BooleanField(default=False, verbose_name='supprimer (douce) — clients')),
                ('supprimer_soft_partenaire', models.BooleanField(default=False, verbose_name='supprimer (douce) — partenaires')),
                ('supprimer_soft_admin', models.BooleanField(default=False, verbose_name='supprimer (douce) — admins')),
                ('supprimer_hard_client', models.BooleanField(default=False, verbose_name='supprimer (définitive) — clients')),
                ('supprimer_hard_partenaire', models.BooleanField(default=False, verbose_name='supprimer (définitive) — partenaires')),
                ('supprimer_hard_admin', models.BooleanField(default=False, verbose_name='supprimer (définitive) — admins')),
                ('restaurer_client', models.BooleanField(default=False, verbose_name='restaurer — clients')),
                ('restaurer_partenaire', models.BooleanField(default=False, verbose_name='restaurer — partenaires')),
                ('restaurer_admin', models.BooleanField(default=False, verbose_name='restaurer — admins')),
                ('masquer_partenaire', models.BooleanField(default=False, verbose_name='masquer / afficher un partenaire')),
                ('certifier_partenaire', models.BooleanField(default=False, verbose_name='donner / retirer le badge certifié')),
                ('accorder_faveur', models.BooleanField(default=False, verbose_name='accorder / retirer une faveur')),
                ('valider_devenir_partenaire', models.BooleanField(default=False, verbose_name='valider une demande « devenir partenaire »')),
                ('valider_publicite', models.BooleanField(default=False, verbose_name='valider / rejeter une publicité')),
                ('offrir_campagne', models.BooleanField(default=False, verbose_name='offrir / retirer une campagne')),
                ('valider_commande', models.BooleanField(default=False, verbose_name='valider / rejeter une commande')),
                ('valider_paiement', models.BooleanField(default=False, verbose_name='valider / rejeter un paiement')),
                ('modifier_plans_formules', models.BooleanField(default=False, verbose_name='modifier les plans et formules')),
                ('voir_stats', models.BooleanField(default=False, verbose_name='voir les stats')),
                ('voir_indicateurs', models.BooleanField(default=False, verbose_name='voir les indicateurs partenaires')),
                ('lire_journal', models.BooleanField(default=False, verbose_name="lire le journal d'audit")),
                ('exporter_csv', models.BooleanField(default=False, verbose_name='exporter en CSV')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_admin', to=settings.AUTH_USER_MODEL, verbose_name='compte admin')),
            ],
            options={
                'verbose_name': 'permissions admin',
                'verbose_name_plural': 'permissions des admins',
            },
        ),
    ]
