# Generated by Django 5.0.6 on 2026-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_permissionsadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)'), ('accorder_faveur', "Octroi d'une faveur"), ('retirer_faveur', "Retrait d'une faveur"), ('accepter_partenaire', 'Demande partenaire acceptée'), ('rejeter_partenaire', 'Demande partenaire rejetée')], max_length=20, verbose_name='action'),
        ),
    ]
