# Generated by Django 5.0.6 on 2026-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_journalmoderation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='creer_partenaire',
            field=models.BooleanField(default=False, verbose_name='créer un partenaire de A à Z (démarcheur)'),
        ),
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)'), ('accorder_faveur', "Octroi d'une faveur"), ('retirer_faveur', "Retrait d'une faveur"), ('accepter_partenaire', 'Demande partenaire acceptée'), ('rejeter_partenaire', 'Demande partenaire rejetée'), ('creer_partenaire', "Création d'un partenaire (démarcheur)")], max_length=20, verbose_name='action'),
        ),
    ]
