# Generated by Django 5.0.6 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_permissionsadmin_creer_partenaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='gerer_admins',
            field=models.BooleanField(default=False, verbose_name='gérer les comptes admins (créer, éditer capacités, révoquer)'),
        ),
    ]
