# Generated by Django 5.0.6 on 2026-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_gerer_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='voir_interventions',
            field=models.BooleanField(default=False, verbose_name="voir les demandes d'intervention (tous artisans)"),
        ),
    ]
