# Generated by Django 5.0.6 on 2026-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_voir_interventions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)'), ('accorder_faveur', "Octroi d'une faveur"), ('retirer_faveur', "Retrait d'une faveur"), ('accepter_partenaire', 'Demande partenaire acceptée'), ('rejeter_partenaire', 'Demande partenaire rejetée'), ('creer_partenaire', "Création d'un partenaire (démarcheur)"), ('pub_paiement_ok', 'Publicité : paiement confirmé'), ('pub_valider', 'Publicité validée'), ('pub_rejeter', 'Publicité rejetée'), ('pub_terminer', 'Publicité terminée')], max_length=20, verbose_name='action'),
        ),
    ]
