# Generated by Django 5.0.6 on 2026-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_journalmoderation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='gerer_geographie',
            field=models.BooleanField(default=False, verbose_name='gérer la géographie (régions, départements, localités, quartiers)'),
        ),
    ]
