# Generated by Django 5.0.6 on 2026-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_permissionsadmin_gerer_formules_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='gerer_commandes',
            field=models.BooleanField(default=False, verbose_name='gérer les commandes (centre de gestion admin)'),
        ),
    ]
