# Generated by Django 5.0.6 on 2026-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_permissionsadmin_gerer_commandes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)'), ('accorder_faveur', "Octroi d'une faveur"), ('retirer_faveur', "Retrait d'une faveur"), ('accepter_partenaire', 'Demande partenaire acceptée'), ('rejeter_partenaire', 'Demande partenaire rejetée'), ('creer_partenaire', "Création d'un partenaire (démarcheur)"), ('pub_paiement_ok', 'Publicité : paiement confirmé'), ('pub_valider', 'Publicité validée'), ('pub_rejeter', 'Publicité rejetée'), ('pub_terminer', 'Publicité terminée'), ('pub_annuler', 'Publicité : soumission annulée'), ('pub_formule_creer', 'Formule pub créée'), ('pub_formule_modif', 'Formule pub modifiée'), ('pub_formule_suppr', 'Formule pub supprimée'), ('pub_formule_desact', 'Formule pub désactivée'), ('pub_formule_react', 'Formule pub réactivée'), ('pub_parametres_maj', 'Paramètres pub modifiés'), ('pub_stats_visibles', 'Stats pub : visibilité partenaire')], max_length=20, verbose_name='action'),
        ),
    ]
