# Generated by Django 5.0.6 on 2026-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_edition_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsadmin',
            name='gerer_locations',
            field=models.BooleanField(default=False, verbose_name='gérer les locations (logements) à la place du loueur'),
        ),
        migrations.AddField(
            model_name='permissionsadmin',
            name='gerer_reservations',
            field=models.BooleanField(default=False, verbose_name='gérer le centre de demandes (visite/réservation)'),
        ),
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('suspendre', 'Suspension'), ('reactiver', 'Réactivation'), ('bannir', 'Bannissement'), ('supprimer_soft', 'Suppression douce'), ('supprimer_hard', 'Suppression définitive'), ('restaurer', 'Restauration (annule suppression douce)'), ('accorder_faveur', "Octroi d'une faveur"), ('retirer_faveur', "Retrait d'une faveur"), ('accepter_partenaire', 'Demande partenaire acceptée'), ('rejeter_partenaire', 'Demande partenaire rejetée'), ('creer_partenaire', "Création d'un partenaire (démarcheur)"), ('pub_paiement_ok', 'Publicité : paiement confirmé'), ('pub_valider', 'Publicité validée'), ('pub_rejeter', 'Publicité rejetée'), ('pub_terminer', 'Publicité terminée'), ('pub_annuler', 'Publicité : soumission annulée'), ('pub_formule_creer', 'Formule pub créée'), ('pub_formule_modif', 'Formule pub modifiée'), ('pub_formule_suppr', 'Formule pub supprimée'), ('pub_formule_desact', 'Formule pub désactivée'), ('pub_formule_react', 'Formule pub réactivée'), ('pub_parametres_maj', 'Paramètres pub modifiés'), ('pub_stats_visibles', 'Stats pub : visibilité partenaire'), ('resto_fiche_modif', 'Fiche restaurant modifiée (admin)'), ('resto_plat_modif', 'Plat modifié (admin)'), ('resto_menu_modif', 'Menu modifié (admin)'), ('partenaire_telephone_modif', 'Numéro de connexion partenaire modifié'), ('geo_rapprochement_partenaire', 'Géographie partenaire rapprochée'), ('partenaire_position', 'Position GPS partenaire modifiée'), ('partenaire_edition', 'Fiche partenaire modifiée (admin)'), ('loc_logement_modif', 'Logement modifié (admin)'), ('loc_dispo_modif', 'Disponibilité de logement modifiée (admin)'), ('cat_creation', 'Catégorie créée'), ('cat_modification', 'Catégorie modifiée'), ('cat_suppression', 'Catégorie supprimée'), ('cat_archivage', 'Catégorie archivée'), ('cat_desarchivage', 'Catégorie désarchivée'), ('param_mots_cles', 'Paramètres : mots-clés de catégorie modifiés'), ('param_ordre_categ', 'Paramètres : ordre des catégories modifié'), ('param_categorie_visib', 'Paramètres : catégorie affichée ou masquée'), ('param_recherche_traite', 'Paramètres : terme sans résultat traité'), ('param_recherche_ignore', 'Paramètres : terme sans résultat ignoré')], max_length=30, verbose_name='action'),
        ),
    ]
