# Generated by Django 5.0.6 on 2026-08-03 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('version_min_obligatoire', models.CharField(default='1.0.0', help_text='En dessous de cette version, la mise à jour est imposée (app bloquée vers le store).', max_length=20, verbose_name='version minimale obligatoire')),
                ('version_conseillee', models.CharField(default='1.0.0', help_text='En dessous, on suggère la mise à jour sans bloquer.', max_length=20, verbose_name='version conseillée')),
                ('lien_store_android', models.URLField(blank=True, verbose_name='lien Play Store (Android)')),
                ('lien_store_ios', models.URLField(blank=True, verbose_name='lien App Store (iOS)')),
                ('message', models.CharField(blank=True, help_text='Facultatif. Ex. « Une nouvelle version corrige des bugs. »', max_length=255, verbose_name='message affiché')),
            ],
            options={
                'verbose_name': 'contrôle de version',
                'verbose_name_plural': 'contrôle de version',
            },
        ),
    ]
