# Generated by Django 5.0.6 on 2026-07-21 10:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilNavigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('mois_reference', models.DateField(verbose_name='mois de référence')),
                ('nb_articles_vus_mois', models.PositiveIntegerField(default=0, verbose_name='articles vus ce mois')),
                ('temps_cumule_secondes_mois', models.PositiveIntegerField(default=0, verbose_name='temps cumulé ce mois (s)')),
                ('categories_consultees', models.JSONField(blank=True, default=dict, help_text='{"slug_categorie": nombre_de_vues}', verbose_name='catégories consultées')),
                ('derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_navigation', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil de navigation',
                'verbose_name_plural': 'profils de navigation',
            },
        ),
        migrations.CreateModel(
            name='TempsSessionUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='début')),
                ('dernier_ping', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernier ping')),
                ('source', models.CharField(choices=[('mobile', 'Application mobile'), ('web', 'Web')], default='mobile', max_length=10, verbose_name='source')),
                ('est_active', models.BooleanField(default=True, verbose_name='active')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_app', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'temps de session utilisateur',
                'verbose_name_plural': 'temps de sessions utilisateurs',
                'ordering': ['-debut'],
                'indexes': [models.Index(fields=['utilisateur', 'debut'], name='analytics_t_utilisa_e551f1_idx')],
            },
        ),
    ]
