# Generated by Django 5.0.6 on 2026-07-21 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('seuil_jours_connexion', models.PositiveIntegerField(default=7, help_text='Client actif si connecté il y a moins de N jours', verbose_name='seuil jours dernière connexion')),
                ('seuil_articles_mois', models.PositiveIntegerField(default=5, verbose_name='seuil articles vus par mois')),
                ('seuil_minutes_mois', models.PositiveIntegerField(default=15, verbose_name='seuil minutes cumulées par mois')),
            ],
            options={
                'verbose_name': 'paramètres analytics',
                'verbose_name_plural': 'paramètres analytics',
            },
        ),
    ]
