# Generated by Django 5.0.6 on 2026-07-21 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_parametresanalytics'),
        ('users', '0003_profilpartenaire_nb_vues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VueVitrine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('annuaire', 'Liste de la categorie'), ('recherche', 'Recherche'), ('article', 'Depuis une fiche article'), ('favoris', 'Liste des favoris'), ('publicite', 'Depuis une publicite'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='source')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_vitrine', to='users.profilpartenaire', verbose_name='partenaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_vitrines', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vue de vitrine',
                'verbose_name_plural': 'vues de vitrine',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['partenaire', 'cree_le'], name='analytics_v_partena_d4c402_idx')],
            },
        ),
    ]
