# Generated by Django 5.0.6 on 2026-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_vuevitrine'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilnavigation',
            name='nb_interactions_mois',
            field=models.PositiveIntegerField(default=0, verbose_name='interactions ce mois'),
        ),
    ]
