# Generated by Django 5.0.6 on 2026-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_profilnavigation_nb_interactions_mois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilnavigation',
            name='nb_interactions_mois',
        ),
        migrations.AddField(
            model_name='profilnavigation',
            name='nb_vues_catalogue_mois',
            field=models.PositiveIntegerField(default=0, verbose_name='vues de catalogue ce mois'),
        ),
    ]
