# Generated by Django 5.0.6 on 2026-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_profilnavigation_nb_interactions_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresanalytics',
            name='seuil_en_ligne_secondes',
            field=models.PositiveIntegerField(default=120, help_text='Un utilisateur est compté "en ligne" si son dernier ping date de moins de N secondes. Le ping est envoyé toutes les 60 s ; garder ce seuil >= 60 (120 = 2 pings de marge).', verbose_name='seuil "en ligne maintenant" (secondes)'),
        ),
    ]
