# Generated by Django 5.0.6 on 2026-08-16 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_parametresanalytics_seuil_en_ligne_secondes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VueServiceLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('onglet', 'Onglet de la barre du bas'), ('autre', 'Autre')], default='onglet', max_length=15, verbose_name='source')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_service_livraison', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vue du service livraison',
                'verbose_name_plural': 'vues du service livraison',
                'ordering': ['-cree_le'],
            },
        ),
    ]
