# Generated by Django 5.0.6 on 2026-06-11 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_adresseclient_horaireouverture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('produit', 'Produit'), ('plat', 'Plat'), ('service', 'Service'), ('logement', 'Logement'), ('vehicule', 'Véhicule'), ('modele_couture', 'Modèle de couture'), ('modele_menuiserie', 'Modèle de menuiserie')], max_length=30, verbose_name='type')),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='prix (FCFA)')),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='prix promotionnel (FCFA)')),
                ('unite', models.CharField(blank=True, help_text='Ex: "par séance", "par jour", "le kilo"…', max_length=30, verbose_name='unité')),
                ('details', models.JSONField(blank=True, default=dict, help_text="Champs variables par type d'article (allergènes, halal, etc.).", verbose_name='détails spécifiques')),
                ('temps_preparation_min', models.IntegerField(blank=True, null=True, verbose_name='temps de préparation (min)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='article actif')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('est_en_promotion', models.BooleanField(default=False, verbose_name='en promotion')),
                ('nb_vues', models.IntegerField(default=0, verbose_name='nombre de vues')),
                ('nb_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('nb_commentaires', models.IntegerField(default=0, verbose_name='nombre de commentaires')),
                ('nb_favoris', models.IntegerField(default=0, verbose_name='nombre de favoris')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.profilcommercant', verbose_name='commerçant')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_principale', models.BooleanField(default=False, verbose_name='image principale')),
                ('est_active', models.BooleanField(default=True, verbose_name='image active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': "image d'article",
                'verbose_name_plural': "images d'articles",
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icone', models.CharField(blank=True, help_text='Emoji ou nom d\'icône (ex: "💇", "pharmacy").', max_length=50, verbose_name='icône')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name="image d'affiche du marché virtuel")),
                ('mode_transaction', models.CharField(choices=[('vitrine_chat', 'Vitrine + Chat'), ('panier_commande', 'Panier + Commande'), ('catalogue_demande_intervention', "Catalogue + Demande d'intervention"), ('demande_intervention', "Demande d'intervention")], default='vitrine_chat', max_length=40, verbose_name='mode de transaction')),
                ('module_flutter', models.CharField(blank=True, help_text='Nom du module Flutter associé (ex: "restaurants", "beaute").', max_length=50, verbose_name='module Flutter')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='catégorie active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text="Vide si racine, sinon la catégorie qui l'englobe.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='catalog.categorie', verbose_name='catégorie parente')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalog.categorie', verbose_name='catégorie'),
        ),
        migrations.CreateModel(
            name='CommercantCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_principale', models.BooleanField(default=False, verbose_name='catégorie principale')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_commercants', to='catalog.categorie', verbose_name='catégorie')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_categories', to='users.profilcommercant', verbose_name='commerçant')),
            ],
            options={
                'verbose_name': "catégorie d'un commerçant",
                'verbose_name_plural': 'catégories des commerçants',
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_chambres', models.IntegerField(default=1, verbose_name='nombre de chambres')),
                ('nb_sdb', models.IntegerField(default=1, verbose_name='nombre de salles de bain')),
                ('surface_m2', models.IntegerField(blank=True, null=True, verbose_name='surface (m²)')),
                ('meuble', models.BooleanField(default=False, verbose_name='meublé')),
                ('duree_min_jours', models.IntegerField(blank=True, null=True, verbose_name='durée minimale (jours)')),
                ('caution', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='caution (FCFA)')),
                ('equipements', models.JSONField(blank=True, default=list, help_text='Liste d\'équipements : ["wifi", "clim", "parking"…]', verbose_name='équipements')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logement', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'logement',
                'verbose_name_plural': 'logements',
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panoramas/', verbose_name='image panoramique 360°')),
                ('nom_piece', models.CharField(blank=True, help_text='Ex: "Salon", "Chambre principale", "Cuisine"…', max_length=100, verbose_name='nom de la pièce')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='panorama actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'panorama 360°',
                'verbose_name_plural': 'panoramas 360°',
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='SectionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom de la section')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='icône')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='section active')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_menu', to='users.profilcommercant', verbose_name='commerçant')),
            ],
            options={
                'verbose_name': 'section de menu',
                'verbose_name_plural': 'sections de menu',
                'ordering': ['commercant', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='section_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.sectionmenu', verbose_name='section du menu'),
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('est_optionnel', models.BooleanField(default=True, verbose_name='optionnel')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='supplément actif')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'supplément',
                'verbose_name_plural': 'suppléments',
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prix_supplement', models.DecimalField(decimal_places=0, default=0, help_text="S'ajoute au prix de base de l'article.", max_digits=10, verbose_name='supplément de prix (FCFA)')),
                ('est_par_defaut', models.BooleanField(default=False, verbose_name='variante par défaut')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='variante active')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='marque')),
                ('modele', models.CharField(max_length=100, verbose_name='modèle')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='année')),
                ('kilometrage', models.IntegerField(blank=True, null=True, verbose_name='kilométrage')),
                ('carburant', models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20, verbose_name='carburant')),
                ('boite_vitesse', models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20, verbose_name='boîte de vitesse')),
                ('places', models.IntegerField(blank=True, null=True, verbose_name='nombre de places')),
                ('mode', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location'), ('les_deux', 'Vente ou location')], default='vente', max_length=20, verbose_name='mode (vente / location)')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
            },
        ),
        migrations.CreateModel(
            name='VueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True, verbose_name='date de la vue')),
                ('source', models.CharField(choices=[('recherche', 'Recherche'), ('categorie', 'Liste de catégorie'), ('carrousel', "Carrousel d'accueil"), ('favoris', 'Liste des favoris'), ('chat', 'Lien depuis un chat'), ('lien_direct', 'Lien direct / partage'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='source')),
                ('duree_secondes', models.IntegerField(blank=True, help_text="Combien de temps l'utilisateur est resté sur la fiche.", null=True, verbose_name='durée de consultation (s)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='catalog.article', verbose_name='article')),
                ('user', models.ForeignKey(blank=True, help_text="Peut être nul si l'utilisateur n'est pas authentifié.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "vue d'article",
                'verbose_name_plural': "vues d'articles",
                'ordering': ['-date_vue'],
            },
        ),
        migrations.AddConstraint(
            model_name='articleimage',
            constraint=models.UniqueConstraint(condition=models.Q(('est_principale', True)), fields=('article',), name='unique_image_principale_par_article'),
        ),
        migrations.AddConstraint(
            model_name='commercantcategorie',
            constraint=models.UniqueConstraint(fields=('commercant', 'categorie'), name='unique_commercant_categorie'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['categorie', 'est_actif'], name='catalog_art_categor_fa1e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['commercant', 'est_actif'], name='catalog_art_commerc_77b0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type'], name='catalog_art_type_5cc202_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('commercant', 'slug'), name='unique_article_commercant_slug'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(condition=models.Q(('est_par_defaut', True)), fields=('article',), name='unique_variante_par_defaut'),
        ),
        migrations.AddIndex(
            model_name='vuearticle',
            index=models.Index(fields=['article', '-date_vue'], name='catalog_vue_article_b59c27_idx'),
        ),
        migrations.AddIndex(
            model_name='vuearticle',
            index=models.Index(fields=['user', '-date_vue'], name='catalog_vue_user_id_421a14_idx'),
        ),
    ]
