# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Vide si racine, sinon la catégorie qui l'englobe.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='catalog.categorie', verbose_name='catégorie parente'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalog.categorie', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='logement',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logement', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='partenairecategorie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_partenaires', to='catalog.categorie', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='partenairecategorie',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_categories', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='sectionmenu',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_menu', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='article',
            name='section_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.sectionmenu', verbose_name='section du menu'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='variante',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='vuearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='vuearticle',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Peut être nul si l'utilisateur n'est pas authentifié.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='articleimage',
            constraint=models.UniqueConstraint(condition=models.Q(('est_principale', True)), fields=('article',), name='unique_image_principale_par_article'),
        ),
        migrations.AddConstraint(
            model_name='partenairecategorie',
            constraint=models.UniqueConstraint(fields=('partenaire', 'categorie'), name='unique_partenaire_categorie'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['categorie', 'est_actif'], name='catalog_art_categor_fa1e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['partenaire', 'est_actif'], name='catalog_art_partena_92083d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type'], name='catalog_art_type_5cc202_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('partenaire', 'slug'), name='unique_article_partenaire_slug'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(condition=models.Q(('est_par_defaut', True)), fields=('article',), name='unique_variante_par_defaut'),
        ),
        migrations.AddIndex(
            model_name='vuearticle',
            index=models.Index(fields=['article', '-date_vue'], name='catalog_vue_article_b59c27_idx'),
        ),
        migrations.AddIndex(
            model_name='vuearticle',
            index=models.Index(fields=['user', '-date_vue'], name='catalog_vue_user_id_421a14_idx'),
        ),
    ]
