# Generated by Django 5.0.6 on 2026-07-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='types_articles',
            field=models.JSONField(blank=True, default=list, help_text='Liste des types proposés au partenaire pour cette catégorie, ex: ["plat", "produit"]. Vide = tous les types.', verbose_name="types d'articles autorisés"),
        ),
    ]
