# Generated by Django 5.0.6 on 2026-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categorie_types_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='est_archivee',
            field=models.BooleanField(default=False, help_text='Archivée = totalement invisible dans l\'application. Désactivée (case active décochée) = grisée "Bientôt disponible".', verbose_name='catégorie archivée'),
        ),
    ]
