# Generated by Django 5.0.6 on 2026-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categorie_est_archivee'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='affiche_catalogue',
            field=models.BooleanField(default=True, help_text='Decoche pour les metiers de service pur (plomberie, electricite...) : le client va directement sur la fiche du partenaire, sans etape catalogue.', verbose_name='affiche un catalogue'),
        ),
    ]
