# Generated by Django 5.0.6 on 2026-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_categorie_affiche_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='types_partenaire',
            field=models.JSONField(blank=True, default=list, help_text="Liste de types (ex. ['plombier']). Un nouveau partenaire de ce type est automatiquement rattaché à cette catégorie.", verbose_name='types de partenaire rattachés'),
        ),
    ]
