# Generated by Django 5.0.6 on 2026-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_categorie_types_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenairecategorie',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text="Facultatif. Permet d'afficher une image differente selon la categorie. Si vide, la photo de couverture du profil est utilisee.", null=True, upload_to='partenaires/couvertures_categories/', verbose_name='photo de couverture (dans cette catégorie)'),
        ),
    ]
