# Generated by Django 5.0.6 on 2026-07-24 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_partenairecategorie_image_couverture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='mots_cles',
            field=models.JSONField(blank=True, default=list, help_text="Synonymes que les clients tapent réellement, ex. ['chaussure', 'basket', 'sandale']. Sans cela, seul le nom exact de la catégorie est trouvé.", verbose_name='mots-clés de recherche'),
        ),
        migrations.CreateModel(
            name='RechercheSansResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(db_index=True, max_length=200, verbose_name='terme recherché')),
                ('nb_occurrences', models.PositiveIntegerField(default=1, verbose_name='nombre de fois')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='première fois')),
                ('vu_le', models.DateTimeField(auto_now=True, verbose_name='dernière fois')),
                ('traite', models.BooleanField(default=False, help_text='Cocher une fois les mots-clés enrichis.', verbose_name='traité')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherches_vides', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'recherche sans résultat',
                'verbose_name_plural': 'recherches sans résultat',
                'ordering': ['-nb_occurrences', '-vu_le'],
            },
        ),
    ]
