# Generated by Django 5.0.6 on 2026-08-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='articles/videos/', verbose_name='vidéo')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('miniature', models.ImageField(blank=True, help_text="Image d'aperçu affichée avant lecture (facultatif).", null=True, upload_to='articles/videos/miniatures/', verbose_name='miniature')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='vidéo active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': "vidéo d'article",
                'verbose_name_plural': "vidéos d'articles",
                'ordering': ['article', 'ordre'],
            },
        ),
    ]
