# Generated by Django 5.0.6 on 2026-10-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_articlevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_reserve_aux_menus',
            field=models.BooleanField(default=False, help_text='Masqué de la carte publique, mais utilisable comme plat dans un menu programmé (ex. plat hors carte).', verbose_name='réservé aux menus'),
        ),
        migrations.CreateModel(
            name='GroupeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('min_choix', models.PositiveSmallIntegerField(default=0, verbose_name='choix minimum')),
                ('max_choix', models.PositiveSmallIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='choix maximum')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='groupe actif')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_options', to='catalog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': "groupe d'options",
                'verbose_name_plural': "groupes d'options",
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prix_supplement', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='supplément de prix (FCFA)')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='option active')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.groupeoption', verbose_name='groupe')),
            ],
            options={
                'verbose_name': 'option de groupe',
                'verbose_name_plural': 'options de groupe',
                'ordering': ['groupe', 'ordre'],
            },
        ),
    ]
