# Generated by Django 5.0.6 on 2026-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_article_est_reserve_aux_menus_groupeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modifie_par_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)'),
        ),
        migrations.AddField(
            model_name='article',
            name='modifie_par_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='modifié par (rôle)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='sectionmenu',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='sectionmenu',
            name='modifie_par_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)'),
        ),
        migrations.AddField(
            model_name='sectionmenu',
            name='modifie_par_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='modifié par (rôle)'),
        ),
    ]
