# Generated by Django 5.0.6 on 2026-10-05 17:10

from django.db import migrations, models


def reprendre_traite(apps, schema_editor):
    RechercheSansResultat = apps.get_model('catalog', 'RechercheSansResultat')
    RechercheSansResultat.objects.filter(traite=True).update(statut='traite')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_article_modifie_par_nom_article_modifie_par_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchesansresultat',
            name='statut',
            field=models.CharField(choices=[('a_traiter', 'À traiter'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='a_traiter', max_length=12, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='recherchesansresultat',
            name='traite',
            field=models.BooleanField(default=False, help_text='Cocher une fois les mots-clés enrichis. Tenu à jour avec statut.', verbose_name='traité'),
        ),
        migrations.RunPython(reprendre_traite, migrations.RunPython.noop),
    ]
