# Generated by Django 5.0.6 on 2026-10-07 12:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_statut_recherche_sans_resultat'),
        ('geo', '0006_departement_cree_le_departement_modifie_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='adresse_reperes',
            field=models.TextField(blank=True, verbose_name='adresse / repères'),
        ),
        migrations.AddField(
            model_name='logement',
            name='avance_mois',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='avance (mois de loyer)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='caution_mois',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='caution (mois de loyer)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='compteur_eau_individuel',
            field=models.BooleanField(default=False, verbose_name='compteur eau individuel'),
        ),
        migrations.AddField(
            model_name='logement',
            name='compteur_electricite_individuel',
            field=models.BooleanField(default=False, verbose_name='compteur électricité individuel'),
        ),
        migrations.AddField(
            model_name='logement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='logement',
            name='disponibilite',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('loue', 'Loué')], default='disponible', max_length=10, verbose_name='disponibilité'),
        ),
        migrations.AddField(
            model_name='logement',
            name='disponible_a_partir_du',
            field=models.DateField(blank=True, null=True, verbose_name='disponible à partir du'),
        ),
        migrations.AddField(
            model_name='logement',
            name='frais_agence',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="frais d'agence (FCFA)"),
        ),
        migrations.AddField(
            model_name='logement',
            name='localisation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='position GPS'),
        ),
        migrations.AddField(
            model_name='logement',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='geo.localite', verbose_name='localité'),
        ),
        migrations.AddField(
            model_name='logement',
            name='modifie_par_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='modifié par (nom)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='modifie_par_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='modifié par (rôle)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='nb_salons',
            field=models.IntegerField(default=1, verbose_name='nombre de salons'),
        ),
        migrations.AddField(
            model_name='logement',
            name='quartier_geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='geo.quartier', verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='logement',
            name='secteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='secteur'),
        ),
        migrations.AddField(
            model_name='logement',
            name='type_logement',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('chambre_salon', 'Chambre-salon'), ('appartement', 'Appartement'), ('villa', 'Villa'), ('maison_basse', 'Maison basse'), ('duplex', 'Duplex'), ('autre', 'Autre')], max_length=20, verbose_name='type de logement'),
        ),
        migrations.AddField(
            model_name='logement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='type_vue',
            field=models.CharField(choices=[('photo_360', 'Photo 360°'), ('panoramique', 'Panoramique')], default='photo_360', max_length=15, verbose_name='type de vue'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='image',
            field=models.ImageField(upload_to='panoramas/', verbose_name='image panoramique'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='nom_piece',
            field=models.CharField(blank=True, help_text='Ex: "Salon", "Chambre principale", "Cuisine"…', max_length=100, verbose_name='nom de la pièce / titre'),
        ),
    ]
