# Generated by Django 5.0.6 on 2026-10-08 09:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_locations_m1"),
        ("geo", "0006_departement_cree_le_departement_modifie_le_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="adresse_reperes",
            field=models.TextField(blank=True, verbose_name="adresse / repères"),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="carburant_inclus",
            field=models.BooleanField(default=False, verbose_name="carburant inclus"),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="categorie_vehicule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("voiture", "Voiture"),
                    ("suv_4x4", "SUV / 4x4"),
                    ("minibus", "Minibus"),
                    ("bus", "Bus"),
                    ("moto", "Moto"),
                    ("tricycle", "Tricycle"),
                    ("autre", "Autre"),
                ],
                max_length=15,
                verbose_name="catégorie de véhicule",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="caution",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="caution (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="chauffeur_disponible",
            field=models.BooleanField(
                default=False, verbose_name="chauffeur disponible"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="chauffeur_obligatoire",
            field=models.BooleanField(
                default=False, verbose_name="chauffeur obligatoire"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="climatisation",
            field=models.BooleanField(default=False, verbose_name="climatisation"),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="couleur",
            field=models.CharField(blank=True, max_length=50, verbose_name="couleur"),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="créé le"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="disponibilite",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("indisponible", "Indisponible"),
                ],
                default="disponible",
                max_length=12,
                verbose_name="disponibilité",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="duree_min_jours",
            field=models.PositiveIntegerField(
                default=1, verbose_name="durée minimale (jours)"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="equipements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste parmi le référentiel apps.locations.services.EQUIPEMENTS_VEHICULE_LIBELLES.",
                verbose_name="équipements",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="km_inclus_par_jour",
            field=models.PositiveIntegerField(
                default=0, verbose_name="km inclus par jour (0 = illimité)"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="localisation",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
                verbose_name="position GPS",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="localite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicules",
                to="geo.localite",
                verbose_name="localité",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="modifie_par_nom",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="modifié par (nom)"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="modifie_par_role",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="modifié par (rôle)"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="prix_jour_avec_chauffeur",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="prix/jour avec chauffeur (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="prix_km_supplementaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="prix du km supplémentaire (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="quartier_geo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicules",
                to="geo.quartier",
                verbose_name="quartier",
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="secteur",
            field=models.CharField(blank=True, max_length=100, verbose_name="secteur"),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="modifié le"
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="zone_circulation",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="zone de circulation"
            ),
        ),
    ]
