# Generated by Django 5.0.6 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_locations_v1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[
                    ("produit", "Produit"),
                    ("plat", "Plat"),
                    ("service", "Service"),
                    ("logement", "Logement"),
                    ("vehicule", "Véhicule"),
                    ("hebergement", "Hébergement (hôtel, résidence)"),
                    ("modele_couture", "Modèle de couture"),
                    ("modele_menuiserie", "Modèle de menuiserie"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="Hebergement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_hebergement",
                    models.CharField(
                        choices=[
                            ("chambre_simple", "Chambre simple"),
                            ("chambre_double", "Chambre double"),
                            ("chambre_twin", "Chambre twin (2 lits)"),
                            ("suite", "Suite"),
                            ("studio", "Studio"),
                            ("appartement", "Appartement"),
                            ("villa", "Villa"),
                        ],
                        max_length=20,
                        verbose_name="type d'hébergement",
                    ),
                ),
                (
                    "capacite_adultes",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="capacité adultes"
                    ),
                ),
                (
                    "capacite_enfants",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="capacité enfants"
                    ),
                ),
                (
                    "lits",
                    models.CharField(
                        blank=True,
                        help_text="Ex. « 1 lit double ».",
                        max_length=100,
                        verbose_name="lits",
                    ),
                ),
                (
                    "surface_m2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="surface (m²)"
                    ),
                ),
                (
                    "equipements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste parmi apps.locations.services.EQUIPEMENTS_HEBERGEMENT_LIBELLES.",
                        verbose_name="équipements",
                    ),
                ),
                (
                    "prix_semaine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix par semaine (FCFA)",
                    ),
                ),
                (
                    "prix_mois",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="prix par mois (FCFA)",
                    ),
                ),
                (
                    "nb_unites",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Chambres identiques disponibles à la vente.",
                        verbose_name="nombre d'unités identiques",
                    ),
                ),
                (
                    "duree_min_nuits",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="durée minimale (nuits)"
                    ),
                ),
                (
                    "disponibilite",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("indisponible", "Indisponible"),
                        ],
                        default="disponible",
                        max_length=12,
                        verbose_name="disponibilité",
                    ),
                ),
                (
                    "modifie_par_role",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="modifié par (rôle)"
                    ),
                ),
                (
                    "modifie_par_nom",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="modifié par (nom)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modifié le"
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hebergement",
                        to="catalog.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "hébergement",
                "verbose_name_plural": "hébergements",
            },
        ),
    ]
