# Generated by Django 5.0.6 on 2026-07-31 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geo.district', verbose_name='district')),
            ],
            options={
                'verbose_name': 'région',
                'verbose_name_plural': 'régions',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour masquer ce département du choix des utilisateurs sans le supprimer.', verbose_name='actif')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='geo.region', verbose_name='région')),
            ],
            options={
                'verbose_name': 'département',
                'verbose_name_plural': 'départements',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('nom', 'district'), name='unique_region_district'),
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('nom', 'region'), name='unique_departement_region'),
        ),
    ]
