# Generated by Django 5.0.6 on 2026-08-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='geo.departement', verbose_name='département')),
            ],
            options={
                'verbose_name': 'quartier',
                'verbose_name_plural': 'quartiers',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(fields=('nom', 'departement'), name='unique_quartier_departement'),
        ),
    ]
