# Generated by Django 5.0.6 on 2026-09-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_quartier_quartier_unique_quartier_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'localité',
                'verbose_name_plural': 'localités',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region_district',
        ),
        migrations.AddField(
            model_name='region',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer cette région du choix des utilisateurs sans la supprimer.', verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='geo.departement', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='localite',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localites', to='geo.departement', verbose_name='département'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='geo.localite', verbose_name='localité'),
        ),
        migrations.AddConstraint(
            model_name='localite',
            constraint=models.UniqueConstraint(fields=('nom', 'departement'), name='unique_localite_departement'),
        ),
    ]
