# Generated by Django 5.0.6 on 2026-09-24 16:09
"""Migration de données : insère le niveau Localité entre Département et
Quartier sans rien perdre.

Pour chaque département référencé par au moins un Quartier existant, crée
une Localité du même nom (l'admin pourra la renommer ensuite si besoin),
puis rattache chaque Quartier à cette Localité. departement reste renseigné
sur Quartier à ce stade (retiré à la migration suivante, une fois
localite garanti non-null) — aucune donnée existante n'est supprimée ici.
"""
from django.db import migrations


def peupler(apps, schema_editor):
    Departement = apps.get_model('geo', 'Departement')
    Localite = apps.get_model('geo', 'Localite')
    Quartier = apps.get_model('geo', 'Quartier')

    departements_utilises = Departement.objects.filter(
        quartiers__isnull=False).distinct()
    for departement in departements_utilises:
        localite, _ = Localite.objects.get_or_create(
            nom=departement.nom, departement=departement,
        )
        Quartier.objects.filter(
            departement=departement, localite__isnull=True,
        ).update(localite=localite)


def revenir(apps, schema_editor):
    # Pas de suppression des Localites creees : reversible sans perte, le
    # departement reste sur Quartier (encore present a ce stade).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_localite_remove_region_unique_region_district_and_more'),
    ]

    operations = [
        migrations.RunPython(peupler, revenir),
    ]
