# Generated by Django 5.0.6 on 2026-09-24 16:09
"""Finalise le passage Quartier.departement -> Quartier.localite.

Écrite à la main (pas de makemigrations auto) car l'assistant interactif de
Django demande un défaut pour le NOT NULL — inutile ici : la migration de
données précédente (0004) a déjà rempli `localite` sur les 9 lignes
existantes, vérifié avant écriture. `departement` est retiré seulement
maintenant, une fois la relève garantie complète.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_peupler_localites_depuis_quartiers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quartier',
            name='unique_quartier_departement',
        ),
        migrations.RemoveField(
            model_name='quartier',
            name='departement',
        ),
        migrations.AlterField(
            model_name='quartier',
            name='localite',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='quartiers', to='geo.localite',
                verbose_name='localité'),
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(
                fields=('nom', 'localite'), name='unique_quartier_localite'),
        ),
    ]
