# Generated by Django 5.0.6 on 2026-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_finaliser_quartier_localite'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='departement',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='localite',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='localite',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='region',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='region',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
    ]
