# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentairePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('est_modifie', models.BooleanField(default=False, verbose_name='modifié')),
                ('nb_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'commentaire - commerçant',
                'verbose_name_plural': 'commentaires - commerçants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'favori - article',
                'verbose_name_plural': 'favoris - articles',
            },
        ),
        migrations.CreateModel(
            name='FavoriPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'favori - commerçant',
                'verbose_name_plural': 'favoris - commerçants',
            },
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "like d'article",
                'verbose_name_plural': "likes d'articles",
            },
        ),
        migrations.CreateModel(
            name='LikeCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'like de commentaire',
                'verbose_name_plural': 'likes de commentaires',
            },
        ),
        migrations.CreateModel(
            name='LikePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'like de commerçant',
                'verbose_name_plural': 'likes de commerçants',
            },
        ),
        migrations.CreateModel(
            name='CommentaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_visible', models.BooleanField(default=True, help_text='Décocher pour masquer le commentaire (modération).', verbose_name='visible')),
                ('est_modifie', models.BooleanField(default=False, verbose_name='modifié')),
                ('nb_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='catalog.article', verbose_name='article')),
                ('parent', models.ForeignKey(blank=True, help_text='Si renseigné, ce commentaire est une réponse.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='social.commentairearticle', verbose_name='réponse à')),
            ],
            options={
                'verbose_name': 'commentaire - article',
                'verbose_name_plural': 'commentaires - articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
