# Generated by Django 5.0.6 on 2026-06-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0004_adresseclient_horaireouverture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_visible', models.BooleanField(default=True, help_text='Décocher pour masquer le commentaire (modération).', verbose_name='visible')),
                ('est_modifie', models.BooleanField(default=False, verbose_name='modifié')),
                ('nb_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='catalog.article', verbose_name='article')),
                ('parent', models.ForeignKey(blank=True, help_text='Si renseigné, ce commentaire est une réponse.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='social.commentairearticle', verbose_name='réponse à')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'commentaire - article',
                'verbose_name_plural': 'commentaires - articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('est_modifie', models.BooleanField(default=False, verbose_name='modifié')),
                ('nb_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='users.profilcommercant', verbose_name='commerçant')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='social.commentairecommercant', verbose_name='réponse à')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_commercants', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'commentaire - commerçant',
                'verbose_name_plural': 'commentaires - commerçants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalog.article', verbose_name='article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'favori - article',
                'verbose_name_plural': 'favoris - articles',
            },
        ),
        migrations.CreateModel(
            name='FavoriCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='users.profilcommercant', verbose_name='commerçant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_commercants', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'favori - commerçant',
                'verbose_name_plural': 'favoris - commerçants',
            },
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.article', verbose_name='article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "like d'article",
                'verbose_name_plural': "likes d'articles",
            },
        ),
        migrations.CreateModel(
            name='LikeCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.commentairearticle', verbose_name='commentaire (article)')),
                ('commentaire_commercant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.commentairecommercant', verbose_name='commentaire (commerçant)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'like de commentaire',
                'verbose_name_plural': 'likes de commentaires',
            },
        ),
        migrations.CreateModel(
            name='LikeCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.profilcommercant', verbose_name='commerçant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commercants', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'like de commerçant',
                'verbose_name_plural': 'likes de commerçants',
            },
        ),
        migrations.AddIndex(
            model_name='commentairearticle',
            index=models.Index(fields=['article', '-created_at'], name='social_comm_article_07700b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentairecommercant',
            index=models.Index(fields=['commercant', '-created_at'], name='social_comm_commerc_20bf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriarticle',
            index=models.Index(fields=['user', '-created_at'], name='social_favo_user_id_2716a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriarticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_favori_article'),
        ),
        migrations.AddIndex(
            model_name='favoricommercant',
            index=models.Index(fields=['user', '-created_at'], name='social_favo_user_id_7f831f_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoricommercant',
            constraint=models.UniqueConstraint(fields=('user', 'commercant'), name='unique_favori_commercant'),
        ),
        migrations.AddIndex(
            model_name='likearticle',
            index=models.Index(fields=['article', '-created_at'], name='social_like_article_a053ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='likearticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like_article'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commentaire_article__isnull', False), ('commentaire_commercant__isnull', True)), models.Q(('commentaire_article__isnull', True), ('commentaire_commercant__isnull', False)), _connector='OR'), name='like_commentaire_exclusif'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.UniqueConstraint(condition=models.Q(('commentaire_article__isnull', False)), fields=('user', 'commentaire_article'), name='unique_like_commentaire_article'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.UniqueConstraint(condition=models.Q(('commentaire_commercant__isnull', False)), fields=('user', 'commentaire_commercant'), name='unique_like_commentaire_commercant'),
        ),
        migrations.AddIndex(
            model_name='likecommercant',
            index=models.Index(fields=['commercant', '-created_at'], name='social_like_commerc_8b14c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='likecommercant',
            constraint=models.UniqueConstraint(fields=('user', 'commercant'), name='unique_like_commercant'),
        ),
    ]
