# Generated by Django 5.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('social', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='commentairepartenaire',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='social.commentairepartenaire', verbose_name='réponse à'),
        ),
        migrations.AddField(
            model_name='commentairepartenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='commentairepartenaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_partenaires', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='favoriarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='favoriarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='favoripartenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='favoripartenaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_partenaires', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='likearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='likearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_articles', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='likecommentaire',
            name='commentaire_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.commentairearticle', verbose_name='commentaire (article)'),
        ),
        migrations.AddField(
            model_name='likecommentaire',
            name='commentaire_partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.commentairepartenaire', verbose_name='commentaire (commerçant)'),
        ),
        migrations.AddField(
            model_name='likecommentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='likepartenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.profilpartenaire', verbose_name='commerçant'),
        ),
        migrations.AddField(
            model_name='likepartenaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_partenaires', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddIndex(
            model_name='commentairearticle',
            index=models.Index(fields=['article', '-created_at'], name='social_comm_article_07700b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentairepartenaire',
            index=models.Index(fields=['partenaire', '-created_at'], name='social_comm_partena_777596_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriarticle',
            index=models.Index(fields=['user', '-created_at'], name='social_favo_user_id_2716a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriarticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_favori_article'),
        ),
        migrations.AddIndex(
            model_name='favoripartenaire',
            index=models.Index(fields=['user', '-created_at'], name='social_favo_user_id_9508f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoripartenaire',
            constraint=models.UniqueConstraint(fields=('user', 'partenaire'), name='unique_favori_partenaire'),
        ),
        migrations.AddIndex(
            model_name='likearticle',
            index=models.Index(fields=['article', '-created_at'], name='social_like_article_a053ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='likearticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like_article'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commentaire_article__isnull', False), ('commentaire_partenaire__isnull', True)), models.Q(('commentaire_article__isnull', True), ('commentaire_partenaire__isnull', False)), _connector='OR'), name='like_commentaire_exclusif'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.UniqueConstraint(condition=models.Q(('commentaire_article__isnull', False)), fields=('user', 'commentaire_article'), name='unique_like_commentaire_article'),
        ),
        migrations.AddConstraint(
            model_name='likecommentaire',
            constraint=models.UniqueConstraint(condition=models.Q(('commentaire_partenaire__isnull', False)), fields=('user', 'commentaire_partenaire'), name='unique_like_commentaire_partenaire'),
        ),
        migrations.AddIndex(
            model_name='likepartenaire',
            index=models.Index(fields=['partenaire', '-created_at'], name='social_like_partena_f13173_idx'),
        ),
        migrations.AddConstraint(
            model_name='likepartenaire',
            constraint=models.UniqueConstraint(fields=('user', 'partenaire'), name='unique_like_partenaire'),
        ),
    ]
